; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+m,+v < %s -epi-pipeline | FileCheck %s

define i64 @vscale() nounwind {
; CHECK-LABEL: vscale:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    srli a0, a0, 3
; CHECK-NEXT:    ret
  %1 = call i64 @llvm.vscale.i64()
  ret i64 %1
}

define i64 @vscale_neg() nounwind {
; CHECK-LABEL: vscale_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    srli a0, a0, 3
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    ret
  %1 = call i64 @llvm.vscale.i64()
  %2 = sub i64 1, %1
  ret i64 %2
}

define i64 @vscale_neg_plus_1() nounwind {
; CHECK-LABEL: vscale_neg_plus_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    srli a0, a0, 3
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    ret
  %1 = call i64 @llvm.vscale.i64()
  %2 = sub i64 0, %1
  ret i64 %2
}

define i64 @vscale_pow2() nounwind {
; CHECK-LABEL: vscale_pow2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    ret
  %1 = call i64 @llvm.vscale.i64()
  %2 = mul i64 64, %1
  ret i64 %2
}

define i64 @vscale_mul() nounwind {
; CHECK-LABEL: vscale_mul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    srli a0, a0, 3
; CHECK-NEXT:    slli a1, a0, 2
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    ret
  %1 = call i64 @llvm.vscale.i64()
  %2 = mul i64 5, %1
  ret i64 %2
}

declare i64 @llvm.vscale.i64()
