; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr +v -o - %s \
; RUN:   -verify-machineinstrs -epi-pipeline | FileCheck %s

; 8 -> 32
define <vscale x 8 x i32> @test_sext_i8_i32_m1(<vscale x 8 x i8> %a) nounwind
; CHECK-LABEL: test_sext_i8_i32_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; CHECK-NEXT:    vsext.vf4 v12, v8
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
{
  %b = sext <vscale x 8 x i8> %a to <vscale x 8 x i32>
  ret <vscale x 8 x i32> %b
}

; 8 -> 64
define <vscale x 8 x i64> @test_sext_i8_i64_m1(<vscale x 8 x i8> %a) nounwind
; CHECK-LABEL: test_sext_i8_i64_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; CHECK-NEXT:    vsext.vf8 v16, v8
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
{
  %b = sext <vscale x 8 x i8> %a to <vscale x 8 x i64>
  ret <vscale x 8 x i64> %b
}

; 16 -> 64
define <vscale x 4 x i64> @test_sext_i16_i64_m1(<vscale x 4 x i16> %a) nounwind
; CHECK-LABEL: test_sext_i16_i64_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; CHECK-NEXT:    vsext.vf4 v12, v8
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
{
  %b = sext <vscale x 4 x i16> %a to <vscale x 4 x i64>
  ret <vscale x 4 x i64> %b
}

define <vscale x 8 x i64> @test_sext_i16_i64_m2(<vscale x 8 x i16> %a) nounwind
; CHECK-LABEL: test_sext_i16_i64_m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; CHECK-NEXT:    vsext.vf4 v16, v8
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
{
  %b = sext <vscale x 8 x i16> %a to <vscale x 8 x i64>
  ret <vscale x 8 x i64> %b
}
