; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+f,+d,+a,+c,+v \
; RUN:    -epi-pipeline -verify-machineinstrs < %s | FileCheck %s

define internal fastcc void @bar(<vscale x 1 x double> %v, i64 %vl) nounwind {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  ret void
}

define void @foo(<vscale x 1 x double> %v, i64 %vl) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    call bar
; CHECK-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  call fastcc void @bar(<vscale x 1 x double> %v, i64  %vl)
  ret void
}
