; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+m,+experimental-v < %s -epi-pipeline | FileCheck %s

%union.anon = type { [512 x i8] }
%union.anon.0 = type { [512 x i8] }

; Function Attrs: nounwind
define void @foo(<vscale x 1 x i64> %x) optnone noinline nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -1040
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 1040
; CHECK-NEXT:    ret
entry:
  %mask_le.i = alloca %union.anon, align 1
  %test_mask.i = alloca %union.anon.0, align 8
  %t9 = bitcast %union.anon.0* %test_mask.i to <vscale x 1 x i64>*
  store <vscale x 1 x i64> %x, <vscale x 1 x i64>* %t9, align 8
  ret void
}

