; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+f,+d,+v -epi-pipeline < %s | FileCheck %s

define <vscale x 1 x double> @test_fneg.f64m1(<vscale x 1 x double> %x) {
; CHECK-LABEL: test_fneg.f64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; CHECK-NEXT:    vfneg.v v8, v8
; CHECK-NEXT:    ret
  %x.neg = fneg <vscale x 1 x double>  %x
  ret <vscale x 1 x double> %x.neg
}

define <vscale x 2 x double> @test_fneg.f64m2(<vscale x 2 x double> %x) {
; CHECK-LABEL: test_fneg.f64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; CHECK-NEXT:    vfneg.v v8, v8
; CHECK-NEXT:    ret
  %x.neg = fneg <vscale x 2 x double>  %x
  ret <vscale x 2 x double> %x.neg
}

define <vscale x 2 x float> @test_fneg.f32m1(<vscale x 2 x float> %x) {
; CHECK-LABEL: test_fneg.f32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfneg.v v8, v8
; CHECK-NEXT:    ret
  %x.neg = fneg <vscale x 2 x float>  %x
  ret <vscale x 2 x float> %x.neg
}
