; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -o - %s \
; RUN:     -mattr=+f,+d,+v,+experimental-zvlsseg -epi-pipeline | FileCheck %s

declare { <vscale x 1 x double>, <vscale x 1 x double> } @llvm.epi.vlseg2.nxv1f64(double *%a, i64 %avl)

define <vscale x 1 x double> @test_vlseg2_f64(double *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, mu
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 1 x double>, <vscale x 1 x double> } @llvm.epi.vlseg2.nxv1f64(double* %a, i64 %avl)
  %y = extractvalue { <vscale x 1 x double>, <vscale x 1 x double> } %x, 0
  ret <vscale x 1 x double> %y
}

declare void @llvm.epi.vsseg2.nxv1f64(<vscale x 1 x double> %first, <vscale x 1 x double> %second, double *%a, i64 %avl)

define void @test_vsseg2_f64(<vscale x 1 x double> %first, <vscale x 1 x double> %second, double *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, mu
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv1f64(<vscale x 1 x double> %first, <vscale x 1 x double> %second, double *%a, i64 %avl)
  ret void
}


declare { <vscale x 2 x float>, <vscale x 2 x float> } @llvm.epi.vlseg2.nxv2f32(float *%a, i64 %avl)

define <vscale x 2 x float> @test_vlseg2_f32(float *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, mu
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 2 x float>, <vscale x 2 x float> } @llvm.epi.vlseg2.nxv2f32(float* %a, i64 %avl)
  %y = extractvalue { <vscale x 2 x float>, <vscale x 2 x float> } %x, 0
  ret <vscale x 2 x float> %y
}

declare void @llvm.epi.vsseg2.nxv2f32(<vscale x 2 x float> %first, <vscale x 2 x float> %second, float *%a, i64 %avl)

define void @test_vsseg2_f32(<vscale x 2 x float> %first, <vscale x 2 x float> %second, float *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, mu
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv2f32(<vscale x 2 x float> %first, <vscale x 2 x float> %second, float *%a, i64 %avl)
  ret void
}


declare { <vscale x 1 x i64>, <vscale x 1 x i64> } @llvm.epi.vlseg2.nxv1i64(i64 *%a, i64 %avl)

define <vscale x 1 x i64> @test_vlseg2_i64(i64 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, mu
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 1 x i64>, <vscale x 1 x i64> } @llvm.epi.vlseg2.nxv1i64(i64* %a, i64 %avl)
  %y = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64> } %x, 0
  ret <vscale x 1 x i64> %y
}

declare void @llvm.epi.vsseg2.nxv1i64(<vscale x 1 x i64> %first, <vscale x 1 x i64> %second, i64 *%a, i64 %avl)

define void @test_vsseg2_i64(<vscale x 1 x i64> %first, <vscale x 1 x i64> %second, i64 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, mu
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv1i64(<vscale x 1 x i64> %first, <vscale x 1 x i64> %second, i64 *%a, i64 %avl)
  ret void
}


declare { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.epi.vlseg2.nxv2i32(i32 *%a, i64 %avl)

define <vscale x 2 x i32> @test_vlseg2_i32(i32 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, mu
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.epi.vlseg2.nxv2i32(i32* %a, i64 %avl)
  %y = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } %x, 0
  ret <vscale x 2 x i32> %y
}

declare void @llvm.epi.vsseg2.nxv2i32(<vscale x 2 x i32> %first, <vscale x 2 x i32> %second, i32 *%a, i64 %avl)

define void @test_vsseg2_i32(<vscale x 2 x i32> %first, <vscale x 2 x i32> %second, i32 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, mu
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv2i32(<vscale x 2 x i32> %first, <vscale x 2 x i32> %second, i32 *%a, i64 %avl)
  ret void
}


declare { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.epi.vlseg2.nxv4i16(i16 *%a, i64 %avl)

define <vscale x 4 x i16> @test_vlseg2_i16(i16 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, ta, mu
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.epi.vlseg2.nxv4i16(i16* %a, i64 %avl)
  %y = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } %x, 0
  ret <vscale x 4 x i16> %y
}

declare void @llvm.epi.vsseg2.nxv4i16(<vscale x 4 x i16> %first, <vscale x 4 x i16> %second, i16 *%a, i64 %avl)

define void @test_vsseg2_i16(<vscale x 4 x i16> %first, <vscale x 4 x i16> %second, i16 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, ta, mu
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv4i16(<vscale x 4 x i16> %first, <vscale x 4 x i16> %second, i16 *%a, i64 %avl)
  ret void
}


declare { <vscale x 8 x i8>, <vscale x 8 x i8> } @llvm.epi.vlseg2.nxv8i8(i8 *%a, i64 %avl)

define <vscale x 8 x i8> @test_vlseg2_i8(i8 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vlseg2_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, mu
; CHECK-NEXT:    vlseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
  %x = call { <vscale x 8 x i8>, <vscale x 8 x i8> } @llvm.epi.vlseg2.nxv8i8(i8* %a, i64 %avl)
  %y = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8> } %x, 0
  ret <vscale x 8 x i8> %y
}

declare void @llvm.epi.vsseg2.nxv8i8(<vscale x 8 x i8> %first, <vscale x 8 x i8> %second, i8 *%a, i64 %avl)

define void @test_vsseg2_i8(<vscale x 8 x i8> %first, <vscale x 8 x i8> %second, i8 *%a, i64 %avl) nounwind {
; CHECK-LABEL: test_vsseg2_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, mu
; CHECK-NEXT:    vsseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
  call void @llvm.epi.vsseg2.nxv8i8(<vscale x 8 x i8> %first, <vscale x 8 x i8> %second, i8 *%a, i64 %avl)
  ret void
}
