; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr +v -o - %s \
; RUN:   -verify-machineinstrs -epi-pipeline | FileCheck %s

; 64 -> 32
define <vscale x 2 x i32> @test_zext_i64_i32_m1(<vscale x 2 x i64> %a) nounwind
; CHECK-LABEL: test_zext_i64_i32_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 2 x i64> %a to <vscale x 2 x i32>
  ret <vscale x 2 x i32> %b
}

define <vscale x 4 x i32> @test_zext_i64_i32_m2(<vscale x 4 x i64> %a) nounwind
; CHECK-LABEL: test_zext_i64_i32_m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; CHECK-NEXT:    vnsrl.wi v12, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 4 x i64> %a to <vscale x 4 x i32>
  ret <vscale x 4 x i32> %b
}

define <vscale x 8 x i32> @test_zext_i64_i32_m4(<vscale x 8 x i64> %a) nounwind
; CHECK-LABEL: test_zext_i64_i32_m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; CHECK-NEXT:    vnsrl.wi v16, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 8 x i64> %a to <vscale x 8 x i32>
  ret <vscale x 8 x i32> %b
}

; 32 -> 16
define <vscale x 4 x i16> @test_zext_i32_i16_m1(<vscale x 4 x i32> %a) nounwind
; CHECK-LABEL: test_zext_i32_i16_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 4 x i32> %a to <vscale x 4 x i16>
  ret <vscale x 4 x i16> %b
}

define <vscale x 8 x i16> @test_zext_i32_i16_m2(<vscale x 8 x i32> %a) nounwind
; CHECK-LABEL: test_zext_i32_i16_m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; CHECK-NEXT:    vnsrl.wi v12, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 8 x i32> %a to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %b
}

define <vscale x 16 x i16> @test_zext_i32_i16_m4(<vscale x 16 x i32> %a) nounwind
; CHECK-LABEL: test_zext_i32_i16_m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m4, ta, ma
; CHECK-NEXT:    vnsrl.wi v16, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 16 x i32> %a to <vscale x 16 x i16>
  ret <vscale x 16 x i16> %b
}

; 16 -> 8
define <vscale x 8 x i8> @test_zext_i16_i8_m1(<vscale x 8 x i16> %a) nounwind
; CHECK-LABEL: test_zext_i16_i8_m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 8 x i16> %a to <vscale x 8 x i8>
  ret <vscale x 8 x i8> %b
}

define <vscale x 16 x i8> @test_zext_i16_i8_m2(<vscale x 16 x i16> %a) nounwind
; CHECK-LABEL: test_zext_i16_i8_m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vnsrl.wi v12, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 16 x i16> %a to <vscale x 16 x i8>
  ret <vscale x 16 x i8> %b
}

define <vscale x 32 x i8> @test_zext_i16_i8_m4(<vscale x 32 x i16> %a) nounwind
; CHECK-LABEL: test_zext_i16_i8_m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m4, ta, ma
; CHECK-NEXT:    vnsrl.wi v16, v8, 0
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
{
  %b = trunc <vscale x 32 x i16> %a to <vscale x 32 x i8>
  ret <vscale x 32 x i8> %b
}
