; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+f,+d,+v -verify-machineinstrs < %s \
; RUN:    -epi-pipeline | FileCheck %s

define <vscale x 1 x i64> @nxv1i64_1(i64* %ptr, <vscale x 1 x i64> %indices, <vscale x 1 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv1i64_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vi v8, v8, 3
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    srli a1, a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (a0), v8, v0.t
; CHECK-NEXT:    ret
  %ptrs = getelementptr i64, i64* %ptr, <vscale x 1 x i64> %indices
  %data = call <vscale x 1 x i64> @llvm.vp.gather.nxv1i64.nxv1p0i64(<vscale x 1 x i64*> %ptrs, <vscale x 1 x i1> %mask, i32 %evl)
  ret <vscale x 1 x i64> %data
}

define <vscale x 1 x i64> @nxv1i64_2(<vscale x 1 x i64*> %ptrs, <vscale x 1 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv1i64_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (zero), v8, v0.t
; CHECK-NEXT:    ret
  %data = call <vscale x 1 x i64> @llvm.vp.gather.nxv1i64.nxv1p0i64(<vscale x 1 x i64*> %ptrs, <vscale x 1 x i1> %mask, i32 %evl)
  ret <vscale x 1 x i64> %data
}

define <vscale x 1 x i64> @nxv1i64_3(i64* %ptr, <vscale x 1 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv1i64_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    slli a0, a1, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (zero), v8, v0.t
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 1 x i64*> undef, i64* %ptr, i32 0
  %splat = shufflevector <vscale x 1 x i64*> %head, <vscale x 1 x i64*> undef, <vscale x 1 x i32> zeroinitializer
  %data = call <vscale x 1 x i64> @llvm.vp.gather.nxv1i64.nxv1p0i64(<vscale x 1 x i64*> %splat, <vscale x 1 x i1> %mask, i32 %evl)
  ret <vscale x 1 x i64> %data
}

define <vscale x 2 x float> @nxv2f32_1(float* %ptr, <vscale x 2 x i32> %indices, <vscale x 2 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv2f32_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m2, ta, ma
; CHECK-NEXT:    vsext.vf2 v10, v8
; CHECK-NEXT:    vsll.vi v10, v10, 2
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    srli a1, a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (a0), v10, v0.t
; CHECK-NEXT:    ret
  %ptrs = getelementptr float, float* %ptr, <vscale x 2 x i32> %indices
  %data = call <vscale x 2 x float> @llvm.vp.gather.nxv2f32.nxv2p0f32(<vscale x 2 x float*> %ptrs, <vscale x 2 x i1> %mask, i32 %evl)
  ret <vscale x 2 x float> %data
}

define <vscale x 2 x float> @nxv2f32_2(<vscale x 2 x float*> %ptrs, <vscale x 2 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv2f32_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v10, (zero), v8, v0.t
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %data = call <vscale x 2 x float> @llvm.vp.gather.nxv2f32.nxv2p0f32(<vscale x 2 x float*> %ptrs, <vscale x 2 x i1> %mask, i32 %evl)
  ret <vscale x 2 x float> %data
}

define <vscale x 2 x float> @nxv2f32_3(float* %ptr, <vscale x 2 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv2f32_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    slli a0, a1, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (zero), v10, v0.t
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 2 x float*> undef, float* %ptr, i32 0
  %splat = shufflevector <vscale x 2 x float*> %head, <vscale x 2 x float*> undef, <vscale x 2 x i32> zeroinitializer
  %data = call <vscale x 2 x float> @llvm.vp.gather.nxv2f32.nxv2p0f32(<vscale x 2 x float*> %splat, <vscale x 2 x i1> %mask, i32 %evl)
  ret <vscale x 2 x float> %data
}

; FIXME: Unsupported.
;define <vscale x 16 x i8> @nxv16i8_1(i8* %ptr, <vscale x 16 x i8> %indices, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %ptrs = getelementptr i8, i8* %ptr, <vscale x 16 x i8> %indices
;  %data = call <vscale x 16 x i8> @llvm.vp.gather.nxv16i8.nxv16p0i8(<vscale x 16 x i8*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i8> %data
;}

;define <vscale x 16 x i8> @nxv16i8_2(<vscale x 16 x i8*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %data = call <vscale x 16 x i8> @llvm.vp.gather.nxv16i8.nxv16p0i8(<vscale x 16 x i8*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i8> %data
;}

;define <vscale x 16 x i8> @nxv16i8_3(i8* %ptr, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %head = insertelement <vscale x 16 x i8*> undef, i8* %ptr, i32 0
;  %splat = shufflevector <vscale x 16 x i8*> %head, <vscale x 16 x i8*> undef, <vscale x 16 x i32> zeroinitializer
;  %data = call <vscale x 16 x i8> @llvm.vp.gather.nxv16i8.nxv16p0i8(<vscale x 16 x i8*> %splat, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i8> %data
;}

; FIXME: Unsupported.
;define <vscale x 16 x i16> @nxv16i16_1(i16* %ptr, <vscale x 16 x i16> %indices, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %ptrs = getelementptr i16, i16* %ptr, <vscale x 16 x i16> %indices
;  %data = call <vscale x 16 x i16> @llvm.vp.gather.nxv16i16.nxv16p0i16(<vscale x 16 x i16*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i16> %data
;}

;define <vscale x 16 x i16> @nxv16i16_2(<vscale x 16 x i16*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %data = call <vscale x 16 x i16> @llvm.vp.gather.nxv16i16.nxv16p0i16(<vscale x 16 x i16*> %ptrs, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i16> %data
;}

;define <vscale x 16 x i16> @nxv16i16_3(i16* %ptr, <vscale x 16 x i16> %indices, <vscale x 16 x i1> %mask, i32 %evl) nounwind {
;  %head = insertelement <vscale x 16 x i16*> undef, i16* %ptr, i32 0
;  %splat = shufflevector <vscale x 16 x i16*> %head, <vscale x 16 x i16*> undef, <vscale x 16 x i32> zeroinitializer
;  %data = call <vscale x 16 x i16> @llvm.vp.gather.nxv16i16.nxv16p0i16(<vscale x 16 x i16*> %splat, <vscale x 16 x i1> %mask, i32 %evl)
;  ret <vscale x 16 x i16> %data
;}

define <vscale x 8 x double> @nxv8f64_1(double* %ptr, <vscale x 8 x i64> %indices, <vscale x 8 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv8f64_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; CHECK-NEXT:    vsll.vi v8, v8, 3
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    srli a1, a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (a0), v8, v0.t
; CHECK-NEXT:    ret
  %ptrs = getelementptr double, double* %ptr, <vscale x 8 x i64> %indices
  %data = call <vscale x 8 x double> @llvm.vp.gather.nxv8f64.nxv8p0f64(<vscale x 8 x double*> %ptrs, <vscale x 8 x i1> %mask, i32 %evl)
  ret <vscale x 8 x double> %data
}

define <vscale x 8 x double> @nxv8f64_2(<vscale x 8 x double*> %ptrs, <vscale x 8 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv8f64_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (zero), v8, v0.t
; CHECK-NEXT:    ret
  %data = call <vscale x 8 x double> @llvm.vp.gather.nxv8f64.nxv8p0f64(<vscale x 8 x double*> %ptrs, <vscale x 8 x i1> %mask, i32 %evl)
  ret <vscale x 8 x double> %data
}

define <vscale x 8 x double> @nxv8f64_3(double* %ptr, <vscale x 8 x i1> %mask, i32 %evl) nounwind {
; CHECK-LABEL: nxv8f64_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    slli a0, a1, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, mu
; CHECK-NEXT:    vluxei64.v v8, (zero), v8, v0.t
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 8 x double*> undef, double* %ptr, i32 0
  %splat = shufflevector <vscale x 8 x double*> %head, <vscale x 8 x double*> undef, <vscale x 8 x i32> zeroinitializer
  %data = call <vscale x 8 x double> @llvm.vp.gather.nxv8f64.nxv8p0f64(<vscale x 8 x double*> %splat, <vscale x 8 x i1> %mask, i32 %evl)
  ret <vscale x 8 x double> %data
}

; LMUL=1
declare <vscale x 1 x i64> @llvm.vp.gather.nxv1i64.nxv1p0i64(<vscale x 1 x i64*>, <vscale x 1 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.gather.nxv2f32.nxv2p0f32(<vscale x 2 x float*>, <vscale x 2 x i1>, i32)

; LMUL>1
declare <vscale x 16 x i8> @llvm.vp.gather.nxv16i8.nxv16p0i8(<vscale x 16 x i8*>, <vscale x 16 x i1>, i32)
declare <vscale x 16 x i16> @llvm.vp.gather.nxv16i16.nxv16p0i16(<vscale x 16 x i16*>, <vscale x 16 x i1>, i32)
declare <vscale x 8 x double> @llvm.vp.gather.nxv8f64.nxv8p0f64(<vscale x 8 x double*>, <vscale x 8 x i1>, i32)
