; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple riscv64 -mattr=+m,+a,+f,+d,+v -S -o - -gvn %s \
; RUN:    | FileCheck %s

; Function Attrs: nounwind
define dso_local void @test_vmfirst() local_unnamed_addr #0 {
; CHECK-LABEL: @test_vmfirst(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A:%.*]] = alloca [128 x i32], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 2 x i32> @llvm.epi.vbroadcast.nxv2i32.i32(i32 0, i64 128)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.epi.mask.cast.nxv2i1.nxv2i32(<vscale x 2 x i32> [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.epi.vmfirst.nxv2i1(<vscale x 2 x i1> [[TMP1]], i64 128)
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[TMP2]], -1
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_END:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.else:
; CHECK-NEXT:    tail call void @abort() #5
; CHECK-NEXT:    unreachable
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast [128 x i32]* [[A]] to i8*
; CHECK-NEXT:    call void @llvm.lifetime.start.p0i8(i64 512, i8* nonnull [[TMP3]]) #6
; CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [128 x i32], [128 x i32]* [[A]], i64 0, i64 0
; CHECK-NEXT:    call void @llvm.memset.p0i8.i64(i8* nonnull align 4 dereferenceable(512) [[TMP3]], i8 0, i64 512, i1 false)
; CHECK-NEXT:    store i32 2, i32* [[ARRAYDECAY]], align 4, !tbaa !2
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast [128 x i32]* [[A]] to <vscale x 2 x i1>*
; CHECK-NEXT:    [[TMP5:%.*]] = load <vscale x 2 x i1>, <vscale x 2 x i1>* [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = tail call i64 @llvm.epi.vmfirst.nxv2i1(<vscale x 2 x i1> [[TMP5]], i64 128)
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i64 [[TMP6]], 0
; CHECK-NEXT:    br i1 [[CMP2]], label [[IF_END5:%.*]], label [[IF_ELSE4:%.*]]
; CHECK:       if.else4:
; CHECK-NEXT:    tail call void @abort() #5
; CHECK-NEXT:    unreachable
; CHECK:       if.end5:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0i8(i64 512, i8* nonnull [[TMP3]]) #6
; CHECK-NEXT:    ret void
;
entry:
  %a = alloca [128 x i32], align 4
  %0 = tail call <vscale x 2 x i32> @llvm.epi.vbroadcast.nxv2i32.i32(i32 0, i64 128)
  %1 = tail call <vscale x 2 x i1> @llvm.epi.mask.cast.nxv2i1.nxv2i32(<vscale x 2 x i32> %0)
  %2 = tail call i64 @llvm.epi.vmfirst.nxv2i1(<vscale x 2 x i1> %1, i64 128)
  %cmp = icmp eq i64 %2, -1
  br i1 %cmp, label %if.end, label %if.else

if.else:                                          ; preds = %entry
  tail call void @abort() #4
  unreachable

if.end:                                           ; preds = %entry
  %3 = bitcast [128 x i32]* %a to i8*
  call void @llvm.lifetime.start.p0i8(i64 512, i8* nonnull %3) #5
  %arraydecay = getelementptr inbounds [128 x i32], [128 x i32]* %a, i64 0, i64 0
  call void @llvm.memset.p0i8.i64(i8* nonnull align 4 dereferenceable(512) %3, i8 0, i64 512, i1 false)
  store i32 2, i32* %arraydecay, align 4, !tbaa !2
  %4 = bitcast [128 x i32]* %a to <vscale x 2 x i1>*
  %5 = load <vscale x 2 x i1>, <vscale x 2 x i1>* %4, align 4
  %6 = tail call i64 @llvm.epi.vmfirst.nxv2i1(<vscale x 2 x i1> %5, i64 128)
  %cmp2 = icmp eq i64 %6, 0
  br i1 %cmp2, label %if.end5, label %if.else4

if.else4:                                         ; preds = %if.end
  tail call void @abort() #4
  unreachable

if.end5:                                          ; preds = %if.end
  call void @llvm.lifetime.end.p0i8(i64 512, i8* nonnull %3) #5
  ret void
}

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1

; Function Attrs: nounwind readnone
declare <vscale x 2 x i32> @llvm.epi.vbroadcast.nxv2i32.i32(i32, i64) #2

; Function Attrs: nounwind readnone
declare <vscale x 2 x i1> @llvm.epi.mask.cast.nxv2i1.nxv2i32(<vscale x 2 x i32>) #2

; Function Attrs: nounwind readnone
declare i64 @llvm.epi.vmfirst.nxv2i1(<vscale x 2 x i1>, i64) #2

; Function Attrs: noreturn
declare dso_local void @abort() local_unnamed_addr #3

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #1

; Function Attrs: argmemonly nounwind willreturn
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #1

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-features"="+a,+c,+d,+v,+f,+m,-relax" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { argmemonly nounwind willreturn }
attributes #2 = { nounwind readnone }
attributes #3 = { noreturn "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-features"="+a,+c,+d,+v,+f,+m,-relax" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #4 = { noreturn nounwind }
attributes #5 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0 (git@repo.hca.bsc.es:EPI/System-Software/llvm-mono.git 3479bb91538826cd24212770a68ba1062fc3d3fe)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"int", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
