; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+v < %s | FileCheck %s

define <vscale x 1 x i1> @splat(<vscale x 1 x i1> %v) {
; CHECK-LABEL: splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf8, ta, mu
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, 1, v0
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, tu, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 2
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    vsetvli a1, zero, e8, mf8, ta, mu
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vmsne.vi v0, v8, 0
; CHECK-NEXT:    ret
    %x = extractelement <vscale x 1 x i1> %v, i32 2
    %t = insertelement <vscale x 1 x i1> undef, i1 %x, i32 0
    %s = shufflevector <vscale x 1 x i1> %t, <vscale x 1 x i1> undef, <vscale x 1 x i32> zeroinitializer
    ret <vscale x 1 x i1> %s
}
