; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+f,+d,+a,+c,+v,+zepi \
; RUN:    -verify-machineinstrs --riscv-no-aliases < %s | FileCheck %s

declare <vscale x 1 x i64> @llvm.epi.vload.nt.nxv1i64(
   <vscale x 1 x i64>* %pa,
   i64 %gvl)

declare <vscale x 1 x i64> @llvm.epi.vadd.nxv1i64.nxv1i64.nxv1i64(<vscale x 1 x i64> %c, <vscale x 1 x i64> %d, i64 %gvl)

define void @test.2(<vscale x 1 x i64> * %pa,
; CHECK-LABEL: test.2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a4, e64, m1, ta, mu, nt
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vs1r.v v10, (a1)
; CHECK-NEXT:    vs1r.v v8, (a2)
; CHECK-NEXT:    c.jr ra
 <vscale x 1 x i64> * %pb,
 <vscale x 1 x i64> * %pc,
 <vscale x 1 x i64> %c,
 <vscale x 1 x i64> %d,

 i64 %flags, i64 %gvl) nounwind {
entry:

 %b = call <vscale x 1 x i64> @llvm.epi.vadd.nxv1i64.nxv1i64.nxv1i64(<vscale x 1 x i64> %c, <vscale x 1 x i64> %d, i64 %gvl)
 %a = call <vscale x 1 x i64> @llvm.epi.vload.nt.nxv1i64(<vscale x 1 x i64>* %pa,    i64 %gvl)

 store <vscale x 1 x i64> %a, <vscale x 1 x i64>* %pb
 store <vscale x 1 x i64> %b, <vscale x 1 x i64>* %pc

 ret void
}

define void @test.3(<vscale x 1 x i64> * %pa,
; CHECK-LABEL: test.3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a4, e64, m1, ta, mu, nt
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vs1r.v v10, (a1)
; CHECK-NEXT:    vs1r.v v8, (a2)
; CHECK-NEXT:    c.jr ra
 <vscale x 1 x i64> * %pb,
 <vscale x 1 x i64> * %pc,
 <vscale x 1 x i64> %c,
 <vscale x 1 x i64> %d,

 i64 %flags, i64 %gvl) nounwind {
entry:

 %a = call <vscale x 1 x i64> @llvm.epi.vload.nt.nxv1i64(<vscale x 1 x i64>* %pa,    i64 %gvl)
 %b = call <vscale x 1 x i64> @llvm.epi.vadd.nxv1i64.nxv1i64.nxv1i64(<vscale x 1 x i64> %c, <vscale x 1 x i64> %d, i64 %gvl)

 store <vscale x 1 x i64> %a, <vscale x 1 x i64>* %pb
 store <vscale x 1 x i64> %b, <vscale x 1 x i64>* %pc

 ret void
}


