; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple riscv64 -mattr=+m,+a,+f,+d,+v < %s \
; RUN:   -epi-pipeline -o - | FileCheck %s

; LMUL = 1
; i64
define <vscale x 1 x i64> @nxv1i64(<vscale x 1 x i64> %va, <vscale x 1 x i64> %vb, i32 %offset) {
; CHECK-LABEL: nxv1i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m1, ta, mu
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    vid.v v10
; CHECK-NEXT:    vmsltu.vx v0, v10, a0
; CHECK-NEXT:    vslideup.vx v10, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    ret
  %vc = call <vscale x 1 x i64> @llvm.experimental.vector.slideleftfill.nxv1i64(
    <vscale x 1 x i64> %va,
    <vscale x 1 x i64> %vb,
    i32 %offset)
  ret <vscale x 1 x i64> %vc
}

declare <vscale x 1 x i64> @llvm.experimental.vector.slideleftfill.nxv1i64(<vscale x 1 x i64> %va, <vscale x 1 x i64> %vb, i32 %offset)

; LMUL = 1
; i32
define <vscale x 2 x i32> @nxv2i32(<vscale x 2 x i32> %va, <vscale x 2 x i32> %vb, i32 %offset) {
; CHECK-LABEL: nxv2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e32, m1, ta, mu
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    vid.v v10
; CHECK-NEXT:    vmsltu.vx v0, v10, a0
; CHECK-NEXT:    vslideup.vx v10, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    ret
  %vc = call <vscale x 2 x i32> @llvm.experimental.vector.slideleftfill.nxv2i32(
    <vscale x 2 x i32> %va,
    <vscale x 2 x i32> %vb,
    i32 %offset)
  ret <vscale x 2 x i32> %vc
}

declare <vscale x 2 x i32> @llvm.experimental.vector.slideleftfill.nxv2i32(<vscale x 2 x i32> %va, <vscale x 2 x i32> %vb, i32 %offset)

; LMUL = 1
; double
define <vscale x 1 x double> @nxv1f64(<vscale x 1 x double> %va, <vscale x 1 x double> %vb, i32 %offset) {
; CHECK-LABEL: nxv1f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m1, ta, mu
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    vid.v v10
; CHECK-NEXT:    vmsltu.vx v0, v10, a0
; CHECK-NEXT:    vslideup.vx v10, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    ret
  %vc = call <vscale x 1 x double> @llvm.experimental.vector.slideleftfill.nxv1f64(
    <vscale x 1 x double> %va,
    <vscale x 1 x double> %vb,
    i32 %offset)
  ret <vscale x 1 x double> %vc
}

declare <vscale x 1 x double> @llvm.experimental.vector.slideleftfill.nxv1f64(<vscale x 1 x double> %va, <vscale x 1 x double> %vb, i32 %offset)

; LMUL = 1
; float
define <vscale x 2 x float> @nxv2f32(<vscale x 2 x float> %va, <vscale x 2 x float> %vb, i32 %offset) {
; CHECK-LABEL: nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e32, m1, ta, mu
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    vid.v v10
; CHECK-NEXT:    vmsltu.vx v0, v10, a0
; CHECK-NEXT:    vslideup.vx v10, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    ret
  %vc = call <vscale x 2 x float> @llvm.experimental.vector.slideleftfill.nxv2f32(
    <vscale x 2 x float> %va,
    <vscale x 2 x float> %vb,
    i32 %offset)
  ret <vscale x 2 x float> %vc
}

declare <vscale x 2 x float> @llvm.experimental.vector.slideleftfill.nxv2f32(<vscale x 2 x float> %va, <vscale x 2 x float> %vb, i32 %offset)

; LMUL = 2
; i64
define <vscale x 2 x i64> @nxv2i64(<vscale x 2 x i64> %va, <vscale x 2 x i64> %vb, i32 %offset) {
; CHECK-LABEL: nxv2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    vid.v v12
; CHECK-NEXT:    vmsltu.vx v0, v12, a0
; CHECK-NEXT:    vslideup.vx v12, v10, a0
; CHECK-NEXT:    vmerge.vvm v8, v12, v8, v0
; CHECK-NEXT:    ret
  %vc = call <vscale x 2 x i64> @llvm.experimental.vector.slideleftfill.nxv2i64(
    <vscale x 2 x i64> %va,
    <vscale x 2 x i64> %vb,
    i32 %offset)
  ret <vscale x 2 x i64> %vc
}

declare <vscale x 2 x i64> @llvm.experimental.vector.slideleftfill.nxv2i64(<vscale x 2 x i64> %va, <vscale x 2 x i64> %vb, i32 %offset)
