; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -target-abi ilp32d -mattr=+f,+d < %s \
; RUN:    | FileCheck %s --check-prefix=CHECK32
; RUN: llc -mtriple=riscv64 -target-abi lp64d -mattr=+f,+d < %s \
; RUN:    | FileCheck %s --check-prefix=CHECK64

declare float     @llvm.sin.f32(float  %Val)
declare double    @llvm.sin.f64(double %Val)
declare float     @llvm.cos.f32(float  %Val)
declare double    @llvm.cos.f64(double %Val)

define dso_local float @fsinf32(float %a) nounwind {
; CHECK32-LABEL: fsinf32:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    tail sinf@plt
;
; CHECK64-LABEL: fsinf32:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    tail sinf@plt
entry:
  %t = call float @llvm.sin.f32(float %a)
  ret float %t
}

define dso_local double @fsinf64(double %a) nounwind {
; CHECK32-LABEL: fsinf64:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    tail sin@plt
;
; CHECK64-LABEL: fsinf64:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    tail sin@plt
entry:
  %t = call double @llvm.sin.f64(double %a)
  ret double %t
}

define dso_local float @fcosf32(float %a) nounwind {
; CHECK32-LABEL: fcosf32:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    tail cosf@plt
;
; CHECK64-LABEL: fcosf32:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    tail cosf@plt
entry:
  %t = call float @llvm.cos.f32(float %a)
  ret float %t
}

define dso_local double @fcosf64(double %a) nounwind {
; CHECK32-LABEL: fcosf64:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    tail cos@plt
;
; CHECK64-LABEL: fcosf64:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    tail cos@plt
entry:
  %t = call double @llvm.cos.f64(double %a)
  ret double %t
}

define dso_local float @fsincosf32(float %a) nounwind {
; CHECK32-LABEL: fsincosf32:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    addi sp, sp, -32
; CHECK32-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; CHECK32-NEXT:    fsd fs0, 16(sp) # 8-byte Folded Spill
; CHECK32-NEXT:    fsd fs1, 8(sp) # 8-byte Folded Spill
; CHECK32-NEXT:    fmv.s fs0, fa0
; CHECK32-NEXT:    call sinf@plt
; CHECK32-NEXT:    fmv.s fs1, fa0
; CHECK32-NEXT:    fmv.s fa0, fs0
; CHECK32-NEXT:    call cosf@plt
; CHECK32-NEXT:    fadd.s fa0, fs1, fa0
; CHECK32-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; CHECK32-NEXT:    fld fs0, 16(sp) # 8-byte Folded Reload
; CHECK32-NEXT:    fld fs1, 8(sp) # 8-byte Folded Reload
; CHECK32-NEXT:    addi sp, sp, 32
; CHECK32-NEXT:    ret
;
; CHECK64-LABEL: fsincosf32:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    addi sp, sp, -32
; CHECK64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fsd fs0, 16(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fsd fs1, 8(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fmv.s fs0, fa0
; CHECK64-NEXT:    call sinf@plt
; CHECK64-NEXT:    fmv.s fs1, fa0
; CHECK64-NEXT:    fmv.s fa0, fs0
; CHECK64-NEXT:    call cosf@plt
; CHECK64-NEXT:    fadd.s fa0, fs1, fa0
; CHECK64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    fld fs0, 16(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    fld fs1, 8(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    addi sp, sp, 32
; CHECK64-NEXT:    ret
entry:
  %t1 = tail call fast float @llvm.sin.f32(float %a)
  %t2 = tail call fast float @llvm.cos.f32(float %a)
  %t3 = fadd float %t1, %t2
  ret float %t3
}

define dso_local double @fsincosf64(double %a) nounwind {
; CHECK32-LABEL: fsincosf64:
; CHECK32:       # %bb.0: # %entry
; CHECK32-NEXT:    addi sp, sp, -32
; CHECK32-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; CHECK32-NEXT:    fsd fs0, 16(sp) # 8-byte Folded Spill
; CHECK32-NEXT:    fsd fs1, 8(sp) # 8-byte Folded Spill
; CHECK32-NEXT:    fmv.d fs0, fa0
; CHECK32-NEXT:    call sin@plt
; CHECK32-NEXT:    fmv.d fs1, fa0
; CHECK32-NEXT:    fmv.d fa0, fs0
; CHECK32-NEXT:    call cos@plt
; CHECK32-NEXT:    fadd.d fa0, fs1, fa0
; CHECK32-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; CHECK32-NEXT:    fld fs0, 16(sp) # 8-byte Folded Reload
; CHECK32-NEXT:    fld fs1, 8(sp) # 8-byte Folded Reload
; CHECK32-NEXT:    addi sp, sp, 32
; CHECK32-NEXT:    ret
;
; CHECK64-LABEL: fsincosf64:
; CHECK64:       # %bb.0: # %entry
; CHECK64-NEXT:    addi sp, sp, -32
; CHECK64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fsd fs0, 16(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fsd fs1, 8(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    fmv.d fs0, fa0
; CHECK64-NEXT:    call sin@plt
; CHECK64-NEXT:    fmv.d fs1, fa0
; CHECK64-NEXT:    fmv.d fa0, fs0
; CHECK64-NEXT:    call cos@plt
; CHECK64-NEXT:    fadd.d fa0, fs1, fa0
; CHECK64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    fld fs0, 16(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    fld fs1, 8(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    addi sp, sp, 32
; CHECK64-NEXT:    ret
entry:
  %t1 = tail call fast double @llvm.sin.f64(double %a)
  %t2 = tail call fast double @llvm.cos.f64(double %a)
  %t3 = fadd double %t1, %t2
  ret double %t3
}
