; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -target-abi lp64d -mattr=+f,+d < %s | \
; RUN:     FileCheck %s

define dso_local float @u64tof32(i64 %x) nounwind {
; CHECK-LABEL: u64tof32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.s.lu fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = uitofp i64 %x to float
  ret float %conv
}

define dso_local float @u32tof32(i32 signext %x) nounwind {
; CHECK-LABEL: u32tof32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.s.wu fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = uitofp i32 %x to float
  ret float %conv
}

define dso_local double @u64tof64(i64 %x) nounwind {
; CHECK-LABEL: u64tof64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.d.lu fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = uitofp i64 %x to double
  ret double %conv
}

define dso_local double @u32tof64(i32 signext %x) nounwind {
; CHECK-LABEL: u32tof64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.d.wu fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = uitofp i32 %x to double
  ret double %conv
}

define dso_local float @s64tof32(i64 %x) nounwind {
; CHECK-LABEL: s64tof32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.s.l fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = sitofp i64 %x to float
  ret float %conv
}

define dso_local float @s32tof32(i32 signext %x) nounwind {
; CHECK-LABEL: s32tof32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.s.w fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = sitofp i32 %x to float
  ret float %conv
}

define dso_local double @s64tof64(i64 %x) nounwind {
; CHECK-LABEL: s64tof64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.d.l fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = sitofp i64 %x to double
  ret double %conv
}

define dso_local double @s32tof64(i32 signext %x) nounwind {
; CHECK-LABEL: s32tof64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcvt.d.w fa0, a0
; CHECK-NEXT:    ret
entry:
  %conv = sitofp i32 %x to double
  ret double %conv
}

define dso_local i64 @f64tos32(double %a) nounwind {
; CHECK-LABEL: f64tos32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.l.d a0, fa0, rtz
; CHECK-NEXT:    ret
  %1 = fptosi double %a to i64
  ret i64 %1
}

define dso_local i64 @f64tou32(double %a) nounwind {
; CHECK-LABEL: f64tou32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.lu.d a0, fa0, rtz
; CHECK-NEXT:    ret
  %1 = fptoui double %a to i64
  ret i64 %1
}
