; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+zepi -riscv-v-vector-bits-min=64 \
; RUN:    -scalable-vectorization=only \
; RUN:    -prefer-predicate-over-epilogue=predicate-dont-vectorize \
; RUN:    -S -O2 < %s  -o - | FileCheck %s --check-prefix=CHECK
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+zepi -riscv-v-vector-bits-min=64 \
; RUN:    -scalable-vectorization=only -interleave-no-scalar-epilogue=true \
; RUN:    -prefer-predicate-over-epilogue=predicate-dont-vectorize \
; RUN:    -S -O2 < %s  -o - | FileCheck %s --check-prefix=INTERLEAVE

; Function Attrs: argmemonly nofree norecurse nosync nounwind
define dso_local void @fu(double* noalias nocapture noundef writeonly %a, double* noalias nocapture noundef readonly %b, i32 noundef signext %n, i32* noalias nocapture noundef readonly %m, i32** nocapture noundef readonly %w) local_unnamed_addr #0 {
; CHECK-LABEL: @fu(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP37:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP37]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = add nsw i64 [[WIDE_TRIP_COUNT]], -1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[INDEX]]
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP0]], i64 3, i64 1)
; CHECK-NEXT:    [[TMP2:%.*]] = trunc i64 [[TMP1]] to i32
; CHECK-NEXT:    [[VP_STEPVECTOR:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_ICMP_ULE:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[VP_STEPVECTOR]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[M:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP3]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]]), !tbaa [[TBAA4:![0-9]+]]
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds double, ptr [[B:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[VP_MASK_NOT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_MASK_SELECT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE]], <vscale x 2 x i1> [[VP_MASK_NOT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP_LOAD3:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP4]], <vscale x 2 x i1> [[VP_MASK_SELECT]], i32 [[TMP2]]), !tbaa [[TBAA8:![0-9]+]]
; CHECK-NEXT:    [[VP_OP:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD3]], <vscale x 2 x double> [[VP_OP_LOAD3]], <vscale x 2 x i1> [[VP_MASK_SELECT]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds ptr, ptr [[W:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[VP_MASK_SELECT4:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE]], <vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP_LOAD5:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP5]], <vscale x 2 x i1> [[VP_MASK_SELECT4]], i32 [[TMP2]]), !tbaa [[TBAA10:![0-9]+]]
; CHECK-NEXT:    [[VP_OP_ICMP6:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD5]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT4]], i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP_SELECT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT4]], <vscale x 2 x i1> [[VP_OP_ICMP6]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_MASK_NOT7:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_MASK_SELECT8:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT4]], <vscale x 2 x i1> [[VP_MASK_NOT7]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP_LOAD9:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP4]], <vscale x 2 x i1> [[VP_MASK_SELECT8]], i32 [[TMP2]]), !tbaa [[TBAA8]]
; CHECK-NEXT:    [[VP_OP10:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD9]], <vscale x 2 x double> [[VP_OP_LOAD9]], <vscale x 2 x i1> [[VP_MASK_SELECT8]], i32 [[TMP2]])
; CHECK-NEXT:    [[VP_MASK_SELECT11:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT4]], <vscale x 2 x i1> [[VP_OP_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_PREDPHI:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT8]], <vscale x 2 x double> [[VP_OP10]], <vscale x 2 x double> [[VP_OP]], i32 [[TMP2]])
; CHECK-NEXT:    [[VP_PREDPHI12:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT11]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds double, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[VP_MASK_OR:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT8]], <vscale x 2 x i1> [[VP_MASK_SELECT11]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_MASK_OR13:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR]], <vscale x 2 x i1> [[VP_MASK_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP2]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI12]], ptr [[TMP6]], <vscale x 2 x i1> [[VP_MASK_OR13]], i32 [[TMP2]]), !tbaa [[TBAA8]]
; CHECK-NEXT:    [[TMP7:%.*]] = and i64 [[TMP1]], 4294967295
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP7]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_COND_CLEANUP]], label [[VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
;
; INTERLEAVE-LABEL: @fu(
; INTERLEAVE-NEXT:  entry:
; INTERLEAVE-NEXT:    [[CMP37:%.*]] = icmp sgt i32 [[N:%.*]], 0
; INTERLEAVE-NEXT:    br i1 [[CMP37]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; INTERLEAVE:       for.body.preheader:
; INTERLEAVE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; INTERLEAVE-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = add nsw i64 [[WIDE_TRIP_COUNT]], -1
; INTERLEAVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; INTERLEAVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 1
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP1]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP3:%.*]] = shl i64 [[TMP2]], 2
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT4:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP3]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT5:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT4]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP4:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP5:%.*]] = mul i64 [[TMP4]], 6
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT7:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP5]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT8:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT7]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP6:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP7:%.*]] = shl i64 [[TMP6]], 3
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT10:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP7]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT11:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT10]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP8:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 10
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT13:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP9]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT14:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT13]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP10:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP11:%.*]] = mul i64 [[TMP10]], 12
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT16:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP11]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT17:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT16]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    [[TMP12:%.*]] = tail call i64 @llvm.vscale.i64()
; INTERLEAVE-NEXT:    [[TMP13:%.*]] = mul i64 [[TMP12]], 14
; INTERLEAVE-NEXT:    [[DOTSPLATINSERT19:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP13]], i64 0
; INTERLEAVE-NEXT:    [[DOTSPLAT20:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT19]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; INTERLEAVE-NEXT:    br label [[VECTOR_BODY:%.*]]
; INTERLEAVE:       vector.body:
; INTERLEAVE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; INTERLEAVE-NEXT:    [[TMP14:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[INDEX]]
; INTERLEAVE-NEXT:    [[TMP15:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP14]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP16:%.*]] = trunc i64 [[TMP15]] to i32
; INTERLEAVE-NEXT:    [[TMP17:%.*]] = sub i64 [[TMP14]], [[TMP15]]
; INTERLEAVE-NEXT:    [[TMP18:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP17]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP19:%.*]] = trunc i64 [[TMP18]] to i32
; INTERLEAVE-NEXT:    [[TMP20:%.*]] = sub i64 [[TMP17]], [[TMP18]]
; INTERLEAVE-NEXT:    [[TMP21:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP20]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP22:%.*]] = trunc i64 [[TMP21]] to i32
; INTERLEAVE-NEXT:    [[TMP23:%.*]] = sub i64 [[TMP20]], [[TMP21]]
; INTERLEAVE-NEXT:    [[TMP24:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP23]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP25:%.*]] = trunc i64 [[TMP24]] to i32
; INTERLEAVE-NEXT:    [[TMP26:%.*]] = sub i64 [[TMP23]], [[TMP24]]
; INTERLEAVE-NEXT:    [[TMP27:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP26]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP28:%.*]] = trunc i64 [[TMP27]] to i32
; INTERLEAVE-NEXT:    [[TMP29:%.*]] = sub i64 [[TMP26]], [[TMP27]]
; INTERLEAVE-NEXT:    [[TMP30:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP29]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP31:%.*]] = trunc i64 [[TMP30]] to i32
; INTERLEAVE-NEXT:    [[TMP32:%.*]] = sub i64 [[TMP29]], [[TMP30]]
; INTERLEAVE-NEXT:    [[TMP33:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP32]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP34:%.*]] = trunc i64 [[TMP33]] to i32
; INTERLEAVE-NEXT:    [[TMP35:%.*]] = sub i64 [[TMP32]], [[TMP33]]
; INTERLEAVE-NEXT:    [[TMP36:%.*]] = tail call i64 @llvm.epi.vsetvl(i64 [[TMP35]], i64 3, i64 1)
; INTERLEAVE-NEXT:    [[TMP37:%.*]] = trunc i64 [[TMP36]] to i32
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR3:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[TMP38:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT]], <vscale x 2 x i64> [[VP_STEPVECTOR3]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR6:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[TMP39:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT5]], <vscale x 2 x i64> [[VP_STEPVECTOR6]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR9:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[TMP40:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT8]], <vscale x 2 x i64> [[VP_STEPVECTOR9]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR12:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[TMP41:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT11]], <vscale x 2 x i64> [[VP_STEPVECTOR12]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR15:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[TMP42:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT14]], <vscale x 2 x i64> [[VP_STEPVECTOR15]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR18:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[TMP43:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT17]], <vscale x 2 x i64> [[VP_STEPVECTOR18]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_STEPVECTOR21:%.*]] = tail call <vscale x 2 x i64> @llvm.experimental.vp.stepvector.nxv2i64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[TMP44:%.*]] = tail call <vscale x 2 x i64> @llvm.vp.add.nxv2i64(<vscale x 2 x i64> [[DOTSPLAT20]], <vscale x 2 x i64> [[VP_STEPVECTOR21]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[VP_STEPVECTOR]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE22:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP38]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE23:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP39]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE24:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP40]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE25:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP41]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE26:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP42]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE27:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP43]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_ICMP_ULE28:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> [[TMP44]], <vscale x 2 x i64> [[BROADCAST_SPLAT]], metadata !"ule", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[TMP45:%.*]] = getelementptr inbounds i32, ptr [[M:%.*]], i64 [[INDEX]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP45]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]]), !tbaa [[TBAA4:![0-9]+]]
; INTERLEAVE-NEXT:    [[TMP46:%.*]] = sext i32 [[TMP16]] to i64
; INTERLEAVE-NEXT:    [[TMP47:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP46]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD29:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP47]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP48:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP49:%.*]] = sext i32 [[TMP48]] to i64
; INTERLEAVE-NEXT:    [[TMP50:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP49]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD30:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP50]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP51:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP52:%.*]] = add i32 [[TMP51]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP53:%.*]] = sext i32 [[TMP52]] to i64
; INTERLEAVE-NEXT:    [[TMP54:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP53]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD31:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP54]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP55:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP56:%.*]] = add i32 [[TMP55]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP57:%.*]] = add i32 [[TMP56]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP58:%.*]] = sext i32 [[TMP57]] to i64
; INTERLEAVE-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP58]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD32:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP59]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP60:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP61:%.*]] = add i32 [[TMP60]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP62:%.*]] = add i32 [[TMP61]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP63:%.*]] = add i32 [[TMP62]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP64:%.*]] = sext i32 [[TMP63]] to i64
; INTERLEAVE-NEXT:    [[TMP65:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP64]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD33:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP65]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP66:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP67:%.*]] = add i32 [[TMP66]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP68:%.*]] = add i32 [[TMP67]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP69:%.*]] = add i32 [[TMP68]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP70:%.*]] = add i32 [[TMP69]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP71:%.*]] = sext i32 [[TMP70]] to i64
; INTERLEAVE-NEXT:    [[TMP72:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP71]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD34:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP72]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[TMP73:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP74:%.*]] = add i32 [[TMP73]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP75:%.*]] = add i32 [[TMP74]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP76:%.*]] = add i32 [[TMP75]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP77:%.*]] = add i32 [[TMP76]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP78:%.*]] = add i32 [[TMP77]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP79:%.*]] = sext i32 [[TMP78]] to i64
; INTERLEAVE-NEXT:    [[TMP80:%.*]] = getelementptr inbounds i32, ptr [[TMP45]], i64 [[TMP79]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD35:%.*]] = tail call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr [[TMP80]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]]), !tbaa [[TBAA4]]
; INTERLEAVE-NEXT:    [[VP_OP_ICMP:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP36:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD29]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP37:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD30]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP38:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD31]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP39:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD32]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP40:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD33]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP41:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD34]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP42:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD35]], <vscale x 2 x i32> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[TMP81:%.*]] = getelementptr inbounds double, ptr [[B:%.*]], i64 [[INDEX]]
; INTERLEAVE-NEXT:    [[VP_MASK_NOT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT43:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP36]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT44:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP37]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT45:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP38]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT46:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP39]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT47:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP40]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT48:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP41]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT49:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP42]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE]], <vscale x 2 x i1> [[VP_MASK_NOT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT50:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE22]], <vscale x 2 x i1> [[VP_MASK_NOT43]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT51:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE23]], <vscale x 2 x i1> [[VP_MASK_NOT44]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT52:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE24]], <vscale x 2 x i1> [[VP_MASK_NOT45]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT53:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE25]], <vscale x 2 x i1> [[VP_MASK_NOT46]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT54:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE26]], <vscale x 2 x i1> [[VP_MASK_NOT47]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT55:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE27]], <vscale x 2 x i1> [[VP_MASK_NOT48]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT56:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE28]], <vscale x 2 x i1> [[VP_MASK_NOT49]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_OP_LOAD57:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP81]], <vscale x 2 x i1> [[VP_MASK_SELECT]], i32 [[TMP16]]), !tbaa [[TBAA8:![0-9]+]]
; INTERLEAVE-NEXT:    [[TMP82:%.*]] = sext i32 [[TMP16]] to i64
; INTERLEAVE-NEXT:    [[TMP83:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP82]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD58:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP83]], <vscale x 2 x i1> [[VP_MASK_SELECT50]], i32 [[TMP19]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP84:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP85:%.*]] = sext i32 [[TMP84]] to i64
; INTERLEAVE-NEXT:    [[TMP86:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP85]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD59:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP86]], <vscale x 2 x i1> [[VP_MASK_SELECT51]], i32 [[TMP22]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP87:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP88:%.*]] = add i32 [[TMP87]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP89:%.*]] = sext i32 [[TMP88]] to i64
; INTERLEAVE-NEXT:    [[TMP90:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP89]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD60:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP90]], <vscale x 2 x i1> [[VP_MASK_SELECT52]], i32 [[TMP25]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP91:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP92:%.*]] = add i32 [[TMP91]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP93:%.*]] = add i32 [[TMP92]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP94:%.*]] = sext i32 [[TMP93]] to i64
; INTERLEAVE-NEXT:    [[TMP95:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP94]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD61:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP95]], <vscale x 2 x i1> [[VP_MASK_SELECT53]], i32 [[TMP28]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP96:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP97:%.*]] = add i32 [[TMP96]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP98:%.*]] = add i32 [[TMP97]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP99:%.*]] = add i32 [[TMP98]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP100:%.*]] = sext i32 [[TMP99]] to i64
; INTERLEAVE-NEXT:    [[TMP101:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP100]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD62:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP101]], <vscale x 2 x i1> [[VP_MASK_SELECT54]], i32 [[TMP31]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP102:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP103:%.*]] = add i32 [[TMP102]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP104:%.*]] = add i32 [[TMP103]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP105:%.*]] = add i32 [[TMP104]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP106:%.*]] = add i32 [[TMP105]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP107:%.*]] = sext i32 [[TMP106]] to i64
; INTERLEAVE-NEXT:    [[TMP108:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP107]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD63:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP108]], <vscale x 2 x i1> [[VP_MASK_SELECT55]], i32 [[TMP34]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP109:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP110:%.*]] = add i32 [[TMP109]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP111:%.*]] = add i32 [[TMP110]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP112:%.*]] = add i32 [[TMP111]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP113:%.*]] = add i32 [[TMP112]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP114:%.*]] = add i32 [[TMP113]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP115:%.*]] = sext i32 [[TMP114]] to i64
; INTERLEAVE-NEXT:    [[TMP116:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP115]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD64:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP116]], <vscale x 2 x i1> [[VP_MASK_SELECT56]], i32 [[TMP37]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[VP_OP:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD57]], <vscale x 2 x double> [[VP_OP_LOAD57]], <vscale x 2 x i1> [[VP_MASK_SELECT]], i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_OP65:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD58]], <vscale x 2 x double> [[VP_OP_LOAD58]], <vscale x 2 x i1> [[VP_MASK_SELECT50]], i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_OP66:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD59]], <vscale x 2 x double> [[VP_OP_LOAD59]], <vscale x 2 x i1> [[VP_MASK_SELECT51]], i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_OP67:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD60]], <vscale x 2 x double> [[VP_OP_LOAD60]], <vscale x 2 x i1> [[VP_MASK_SELECT52]], i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_OP68:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD61]], <vscale x 2 x double> [[VP_OP_LOAD61]], <vscale x 2 x i1> [[VP_MASK_SELECT53]], i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_OP69:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD62]], <vscale x 2 x double> [[VP_OP_LOAD62]], <vscale x 2 x i1> [[VP_MASK_SELECT54]], i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_OP70:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD63]], <vscale x 2 x double> [[VP_OP_LOAD63]], <vscale x 2 x i1> [[VP_MASK_SELECT55]], i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_OP71:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fmul.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD64]], <vscale x 2 x double> [[VP_OP_LOAD64]], <vscale x 2 x i1> [[VP_MASK_SELECT56]], i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[TMP117:%.*]] = getelementptr inbounds ptr, ptr [[W:%.*]], i64 [[INDEX]]
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT72:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE]], <vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT73:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE22]], <vscale x 2 x i1> [[VP_OP_ICMP36]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT74:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE23]], <vscale x 2 x i1> [[VP_OP_ICMP37]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT75:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE24]], <vscale x 2 x i1> [[VP_OP_ICMP38]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT76:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE25]], <vscale x 2 x i1> [[VP_OP_ICMP39]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT77:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE26]], <vscale x 2 x i1> [[VP_OP_ICMP40]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT78:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE27]], <vscale x 2 x i1> [[VP_OP_ICMP41]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT79:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_ICMP_ULE28]], <vscale x 2 x i1> [[VP_OP_ICMP42]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_OP_LOAD80:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP117]], <vscale x 2 x i1> [[VP_MASK_SELECT72]], i32 [[TMP16]]), !tbaa [[TBAA10:![0-9]+]]
; INTERLEAVE-NEXT:    [[TMP118:%.*]] = sext i32 [[TMP16]] to i64
; INTERLEAVE-NEXT:    [[TMP119:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP118]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD81:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP119]], <vscale x 2 x i1> [[VP_MASK_SELECT73]], i32 [[TMP19]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP120:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP121:%.*]] = sext i32 [[TMP120]] to i64
; INTERLEAVE-NEXT:    [[TMP122:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP121]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD82:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP122]], <vscale x 2 x i1> [[VP_MASK_SELECT74]], i32 [[TMP22]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP123:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP124:%.*]] = add i32 [[TMP123]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP125:%.*]] = sext i32 [[TMP124]] to i64
; INTERLEAVE-NEXT:    [[TMP126:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP125]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD83:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP126]], <vscale x 2 x i1> [[VP_MASK_SELECT75]], i32 [[TMP25]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP127:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP128:%.*]] = add i32 [[TMP127]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP129:%.*]] = add i32 [[TMP128]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP130:%.*]] = sext i32 [[TMP129]] to i64
; INTERLEAVE-NEXT:    [[TMP131:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP130]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD84:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP131]], <vscale x 2 x i1> [[VP_MASK_SELECT76]], i32 [[TMP28]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP132:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP133:%.*]] = add i32 [[TMP132]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP134:%.*]] = add i32 [[TMP133]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP135:%.*]] = add i32 [[TMP134]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP136:%.*]] = sext i32 [[TMP135]] to i64
; INTERLEAVE-NEXT:    [[TMP137:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP136]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD85:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP137]], <vscale x 2 x i1> [[VP_MASK_SELECT77]], i32 [[TMP31]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP138:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP139:%.*]] = add i32 [[TMP138]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP140:%.*]] = add i32 [[TMP139]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP141:%.*]] = add i32 [[TMP140]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP142:%.*]] = add i32 [[TMP141]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP143:%.*]] = sext i32 [[TMP142]] to i64
; INTERLEAVE-NEXT:    [[TMP144:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP143]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD86:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP144]], <vscale x 2 x i1> [[VP_MASK_SELECT78]], i32 [[TMP34]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[TMP145:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP146:%.*]] = add i32 [[TMP145]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP147:%.*]] = add i32 [[TMP146]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP148:%.*]] = add i32 [[TMP147]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP149:%.*]] = add i32 [[TMP148]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP150:%.*]] = add i32 [[TMP149]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP151:%.*]] = sext i32 [[TMP150]] to i64
; INTERLEAVE-NEXT:    [[TMP152:%.*]] = getelementptr inbounds ptr, ptr [[TMP117]], i64 [[TMP151]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD87:%.*]] = tail call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr [[TMP152]], <vscale x 2 x i1> [[VP_MASK_SELECT79]], i32 [[TMP37]]), !tbaa [[TBAA10]]
; INTERLEAVE-NEXT:    [[VP_OP_ICMP88:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD80]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT72]], i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT72]], <vscale x 2 x i1> [[VP_OP_ICMP88]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP89:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD81]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT73]], i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT90:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT73]], <vscale x 2 x i1> [[VP_OP_ICMP89]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP91:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD82]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT74]], i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT92:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT74]], <vscale x 2 x i1> [[VP_OP_ICMP91]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP93:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD83]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT75]], i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT94:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT75]], <vscale x 2 x i1> [[VP_OP_ICMP93]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP95:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD84]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT76]], i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT96:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT76]], <vscale x 2 x i1> [[VP_OP_ICMP95]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP97:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD85]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT77]], i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT98:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT77]], <vscale x 2 x i1> [[VP_OP_ICMP97]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP99:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD86]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT78]], i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT100:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT78]], <vscale x 2 x i1> [[VP_OP_ICMP99]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_OP_ICMP101:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VP_OP_LOAD87]], <vscale x 2 x ptr> zeroinitializer, metadata !"eq", <vscale x 2 x i1> [[VP_MASK_SELECT79]], i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_OP_SELECT102:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT79]], <vscale x 2 x i1> [[VP_OP_ICMP101]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT103:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT104:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT90]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT105:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT92]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT106:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT94]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT107:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT96]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT108:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT98]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT109:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT100]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_NOT110:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> [[VP_OP_SELECT102]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT111:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT72]], <vscale x 2 x i1> [[VP_MASK_NOT103]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT112:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT73]], <vscale x 2 x i1> [[VP_MASK_NOT104]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT113:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT74]], <vscale x 2 x i1> [[VP_MASK_NOT105]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT114:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT75]], <vscale x 2 x i1> [[VP_MASK_NOT106]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT115:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT76]], <vscale x 2 x i1> [[VP_MASK_NOT107]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT116:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT77]], <vscale x 2 x i1> [[VP_MASK_NOT108]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT117:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT78]], <vscale x 2 x i1> [[VP_MASK_NOT109]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT118:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT79]], <vscale x 2 x i1> [[VP_MASK_NOT110]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_OP_LOAD119:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP81]], <vscale x 2 x i1> [[VP_MASK_SELECT111]], i32 [[TMP16]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP153:%.*]] = sext i32 [[TMP16]] to i64
; INTERLEAVE-NEXT:    [[TMP154:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP153]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD120:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP154]], <vscale x 2 x i1> [[VP_MASK_SELECT112]], i32 [[TMP19]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP155:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP156:%.*]] = sext i32 [[TMP155]] to i64
; INTERLEAVE-NEXT:    [[TMP157:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP156]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD121:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP157]], <vscale x 2 x i1> [[VP_MASK_SELECT113]], i32 [[TMP22]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP158:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP159:%.*]] = add i32 [[TMP158]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP160:%.*]] = sext i32 [[TMP159]] to i64
; INTERLEAVE-NEXT:    [[TMP161:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP160]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD122:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP161]], <vscale x 2 x i1> [[VP_MASK_SELECT114]], i32 [[TMP25]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP162:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP163:%.*]] = add i32 [[TMP162]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP164:%.*]] = add i32 [[TMP163]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP165:%.*]] = sext i32 [[TMP164]] to i64
; INTERLEAVE-NEXT:    [[TMP166:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP165]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD123:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP166]], <vscale x 2 x i1> [[VP_MASK_SELECT115]], i32 [[TMP28]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP167:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP168:%.*]] = add i32 [[TMP167]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP169:%.*]] = add i32 [[TMP168]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP170:%.*]] = add i32 [[TMP169]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP171:%.*]] = sext i32 [[TMP170]] to i64
; INTERLEAVE-NEXT:    [[TMP172:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP171]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD124:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP172]], <vscale x 2 x i1> [[VP_MASK_SELECT116]], i32 [[TMP31]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP173:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP174:%.*]] = add i32 [[TMP173]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP175:%.*]] = add i32 [[TMP174]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP176:%.*]] = add i32 [[TMP175]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP177:%.*]] = add i32 [[TMP176]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP178:%.*]] = sext i32 [[TMP177]] to i64
; INTERLEAVE-NEXT:    [[TMP179:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP178]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD125:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP179]], <vscale x 2 x i1> [[VP_MASK_SELECT117]], i32 [[TMP34]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP180:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP181:%.*]] = add i32 [[TMP180]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP182:%.*]] = add i32 [[TMP181]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP183:%.*]] = add i32 [[TMP182]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP184:%.*]] = add i32 [[TMP183]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP185:%.*]] = add i32 [[TMP184]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP186:%.*]] = sext i32 [[TMP185]] to i64
; INTERLEAVE-NEXT:    [[TMP187:%.*]] = getelementptr inbounds double, ptr [[TMP81]], i64 [[TMP186]]
; INTERLEAVE-NEXT:    [[VP_OP_LOAD126:%.*]] = tail call <vscale x 2 x double> @llvm.vp.load.nxv2f64.p0(ptr [[TMP187]], <vscale x 2 x i1> [[VP_MASK_SELECT118]], i32 [[TMP37]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[VP_OP127:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD119]], <vscale x 2 x double> [[VP_OP_LOAD119]], <vscale x 2 x i1> [[VP_MASK_SELECT111]], i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_OP128:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD120]], <vscale x 2 x double> [[VP_OP_LOAD120]], <vscale x 2 x i1> [[VP_MASK_SELECT112]], i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_OP129:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD121]], <vscale x 2 x double> [[VP_OP_LOAD121]], <vscale x 2 x i1> [[VP_MASK_SELECT113]], i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_OP130:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD122]], <vscale x 2 x double> [[VP_OP_LOAD122]], <vscale x 2 x i1> [[VP_MASK_SELECT114]], i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_OP131:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD123]], <vscale x 2 x double> [[VP_OP_LOAD123]], <vscale x 2 x i1> [[VP_MASK_SELECT115]], i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_OP132:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD124]], <vscale x 2 x double> [[VP_OP_LOAD124]], <vscale x 2 x i1> [[VP_MASK_SELECT116]], i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_OP133:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD125]], <vscale x 2 x double> [[VP_OP_LOAD125]], <vscale x 2 x i1> [[VP_MASK_SELECT117]], i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_OP134:%.*]] = tail call <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VP_OP_LOAD126]], <vscale x 2 x double> [[VP_OP_LOAD126]], <vscale x 2 x i1> [[VP_MASK_SELECT118]], i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT135:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT72]], <vscale x 2 x i1> [[VP_OP_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT136:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT73]], <vscale x 2 x i1> [[VP_OP_SELECT90]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT137:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT74]], <vscale x 2 x i1> [[VP_OP_SELECT92]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT138:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT75]], <vscale x 2 x i1> [[VP_OP_SELECT94]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT139:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT76]], <vscale x 2 x i1> [[VP_OP_SELECT96]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT140:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT77]], <vscale x 2 x i1> [[VP_OP_SELECT98]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT141:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT78]], <vscale x 2 x i1> [[VP_OP_SELECT100]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_SELECT142:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.and.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT79]], <vscale x 2 x i1> [[VP_OP_SELECT102]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT111]], <vscale x 2 x double> [[VP_OP127]], <vscale x 2 x double> [[VP_OP]], i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI143:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT112]], <vscale x 2 x double> [[VP_OP128]], <vscale x 2 x double> [[VP_OP65]], i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI144:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT113]], <vscale x 2 x double> [[VP_OP129]], <vscale x 2 x double> [[VP_OP66]], i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI145:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT114]], <vscale x 2 x double> [[VP_OP130]], <vscale x 2 x double> [[VP_OP67]], i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI146:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT115]], <vscale x 2 x double> [[VP_OP131]], <vscale x 2 x double> [[VP_OP68]], i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI147:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT116]], <vscale x 2 x double> [[VP_OP132]], <vscale x 2 x double> [[VP_OP69]], i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI148:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT117]], <vscale x 2 x double> [[VP_OP133]], <vscale x 2 x double> [[VP_OP70]], i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI149:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT118]], <vscale x 2 x double> [[VP_OP134]], <vscale x 2 x double> [[VP_OP71]], i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI150:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT135]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI]], i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI151:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT136]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI143]], i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI152:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT137]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI144]], i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI153:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT138]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI145]], i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI154:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT139]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI146]], i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI155:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT140]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI147]], i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI156:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT141]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI148]], i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_PREDPHI157:%.*]] = tail call <vscale x 2 x double> @llvm.vp.select.nxv2f64(<vscale x 2 x i1> [[VP_MASK_SELECT142]], <vscale x 2 x double> shufflevector (<vscale x 2 x double> insertelement (<vscale x 2 x double> poison, double 3.000000e+00, i64 0), <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> [[VP_PREDPHI149]], i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[TMP188:%.*]] = getelementptr inbounds double, ptr [[A:%.*]], i64 [[INDEX]]
; INTERLEAVE-NEXT:    [[VP_MASK_OR:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT111]], <vscale x 2 x i1> [[VP_MASK_SELECT135]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR158:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT112]], <vscale x 2 x i1> [[VP_MASK_SELECT136]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR159:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT113]], <vscale x 2 x i1> [[VP_MASK_SELECT137]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR160:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT114]], <vscale x 2 x i1> [[VP_MASK_SELECT138]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR161:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT115]], <vscale x 2 x i1> [[VP_MASK_SELECT139]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR162:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT116]], <vscale x 2 x i1> [[VP_MASK_SELECT140]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR163:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT117]], <vscale x 2 x i1> [[VP_MASK_SELECT141]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR164:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_SELECT118]], <vscale x 2 x i1> [[VP_MASK_SELECT142]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR165:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR]], <vscale x 2 x i1> [[VP_MASK_SELECT]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR166:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR158]], <vscale x 2 x i1> [[VP_MASK_SELECT50]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP19]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR167:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR159]], <vscale x 2 x i1> [[VP_MASK_SELECT51]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP22]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR168:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR160]], <vscale x 2 x i1> [[VP_MASK_SELECT52]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP25]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR169:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR161]], <vscale x 2 x i1> [[VP_MASK_SELECT53]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP28]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR170:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR162]], <vscale x 2 x i1> [[VP_MASK_SELECT54]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP31]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR171:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR163]], <vscale x 2 x i1> [[VP_MASK_SELECT55]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP34]])
; INTERLEAVE-NEXT:    [[VP_MASK_OR172:%.*]] = tail call <vscale x 2 x i1> @llvm.vp.or.nxv2i1(<vscale x 2 x i1> [[VP_MASK_OR164]], <vscale x 2 x i1> [[VP_MASK_SELECT56]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i64 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP37]])
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI150]], ptr [[TMP188]], <vscale x 2 x i1> [[VP_MASK_OR165]], i32 [[TMP16]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP189:%.*]] = sext i32 [[TMP16]] to i64
; INTERLEAVE-NEXT:    [[TMP190:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP189]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI151]], ptr [[TMP190]], <vscale x 2 x i1> [[VP_MASK_OR166]], i32 [[TMP19]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP191:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP192:%.*]] = sext i32 [[TMP191]] to i64
; INTERLEAVE-NEXT:    [[TMP193:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP192]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI152]], ptr [[TMP193]], <vscale x 2 x i1> [[VP_MASK_OR167]], i32 [[TMP22]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP194:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP195:%.*]] = add i32 [[TMP194]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP196:%.*]] = sext i32 [[TMP195]] to i64
; INTERLEAVE-NEXT:    [[TMP197:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP196]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI153]], ptr [[TMP197]], <vscale x 2 x i1> [[VP_MASK_OR168]], i32 [[TMP25]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP198:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP199:%.*]] = add i32 [[TMP198]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP200:%.*]] = add i32 [[TMP199]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP201:%.*]] = sext i32 [[TMP200]] to i64
; INTERLEAVE-NEXT:    [[TMP202:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP201]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI154]], ptr [[TMP202]], <vscale x 2 x i1> [[VP_MASK_OR169]], i32 [[TMP28]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP203:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP204:%.*]] = add i32 [[TMP203]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP205:%.*]] = add i32 [[TMP204]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP206:%.*]] = add i32 [[TMP205]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP207:%.*]] = sext i32 [[TMP206]] to i64
; INTERLEAVE-NEXT:    [[TMP208:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP207]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI155]], ptr [[TMP208]], <vscale x 2 x i1> [[VP_MASK_OR170]], i32 [[TMP31]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP209:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP210:%.*]] = add i32 [[TMP209]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP211:%.*]] = add i32 [[TMP210]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP212:%.*]] = add i32 [[TMP211]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP213:%.*]] = add i32 [[TMP212]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP214:%.*]] = sext i32 [[TMP213]] to i64
; INTERLEAVE-NEXT:    [[TMP215:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP214]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI156]], ptr [[TMP215]], <vscale x 2 x i1> [[VP_MASK_OR171]], i32 [[TMP34]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP216:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP217:%.*]] = add i32 [[TMP216]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP218:%.*]] = add i32 [[TMP217]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP219:%.*]] = add i32 [[TMP218]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP220:%.*]] = add i32 [[TMP219]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP221:%.*]] = add i32 [[TMP220]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP222:%.*]] = sext i32 [[TMP221]] to i64
; INTERLEAVE-NEXT:    [[TMP223:%.*]] = getelementptr inbounds double, ptr [[TMP188]], i64 [[TMP222]]
; INTERLEAVE-NEXT:    tail call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[VP_PREDPHI157]], ptr [[TMP223]], <vscale x 2 x i1> [[VP_MASK_OR172]], i32 [[TMP37]]), !tbaa [[TBAA8]]
; INTERLEAVE-NEXT:    [[TMP224:%.*]] = add i32 [[TMP16]], [[TMP19]]
; INTERLEAVE-NEXT:    [[TMP225:%.*]] = add i32 [[TMP224]], [[TMP22]]
; INTERLEAVE-NEXT:    [[TMP226:%.*]] = add i32 [[TMP225]], [[TMP25]]
; INTERLEAVE-NEXT:    [[TMP227:%.*]] = add i32 [[TMP226]], [[TMP28]]
; INTERLEAVE-NEXT:    [[TMP228:%.*]] = add i32 [[TMP227]], [[TMP31]]
; INTERLEAVE-NEXT:    [[TMP229:%.*]] = add i32 [[TMP228]], [[TMP34]]
; INTERLEAVE-NEXT:    [[TMP230:%.*]] = add i32 [[TMP229]], [[TMP37]]
; INTERLEAVE-NEXT:    [[TMP231:%.*]] = zext i32 [[TMP230]] to i64
; INTERLEAVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP231]]
; INTERLEAVE-NEXT:    [[TMP232:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[WIDE_TRIP_COUNT]]
; INTERLEAVE-NEXT:    br i1 [[TMP232]], label [[FOR_COND_CLEANUP]], label [[VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; INTERLEAVE:       for.cond.cleanup:
; INTERLEAVE-NEXT:    ret void
;
entry:
  %cmp37 = icmp sgt i32 %n, 0
  br i1 %cmp37, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext i32 %n to i64
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.inc
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  ret void

for.body:                                         ; preds = %for.body.preheader, %for.inc
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.inc ]
  %arrayidx = getelementptr inbounds i32, i32* %m, i64 %indvars.iv
  %0 = load i32, i32* %arrayidx, align 4, !tbaa !4
  %tobool.not = icmp eq i32 %0, 0
  br i1 %tobool.not, label %if.else, label %if.then

if.then:                                          ; preds = %for.body
  %arrayidx2 = getelementptr inbounds double, double* %b, i64 %indvars.iv
  %1 = load double, double* %arrayidx2, align 8, !tbaa !8
  %mul = fmul double %1, %1
  br label %for.inc

if.else:                                          ; preds = %for.body
  %arrayidx8 = getelementptr inbounds i32*, i32** %w, i64 %indvars.iv
  %2 = load i32*, i32** %arrayidx8, align 8, !tbaa !10
  %tobool9.not = icmp eq i32* %2, null
  br i1 %tobool9.not, label %for.inc, label %if.then10

if.then10:                                        ; preds = %if.else
  %arrayidx12 = getelementptr inbounds double, double* %b, i64 %indvars.iv
  %3 = load double, double* %arrayidx12, align 8, !tbaa !8
  %add = fadd double %3, %3
  br label %for.inc

for.inc:                                          ; preds = %if.else, %if.then, %if.then10
  %mul.sink = phi double [ %mul, %if.then ], [ %add, %if.then10 ], [ 3.000000e+00, %if.else ]
  %arrayidx6 = getelementptr inbounds double, double* %a, i64 %indvars.iv
  store double %mul.sink, double* %arrayidx6, align 8, !tbaa !8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup.loopexit, label %for.body, !llvm.loop !12
}

attributes #0 = { argmemonly nofree norecurse nosync nounwind "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+a,+c,+d,+f,+m,+zepi,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvl32b,+zvl64b,-relax,-save-restore" }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"lp64d"}
!2 = !{i32 1, !"SmallDataLimit", i32 8}
!3 = !{!"clang version 15.0.0"}
!4 = !{!5, !5, i64 0}
!5 = !{!"int", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !9, i64 0}
!9 = !{!"double", !6, i64 0}
!10 = !{!11, !11, i64 0}
!11 = !{!"any pointer", !6, i64 0}
!12 = distinct !{!12, !13}
!13 = !{!"llvm.loop.mustprogress"}
