; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+experimental-v \
; RUN:    -prefer-predicate-over-epilogue=predicate-dont-vectorize -S -loop-vectorize -vector-register-width-factor=8 < %s -o - \
; RUN:    | FileCheck %s
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+experimental-v \
; RUN:    -prefer-predicate-over-epilogue=predicate-dont-vectorize -S -loop-vectorize < %s -o - \
; RUN:    | FileCheck %s --check-prefix=CHECK1
; ModuleID = './simple-add-control-flow.c'
source_filename = "./simple-add-control-flow.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128-v128:128:128-v256:128:128-v512:128:128-v1024:128:128"
target triple = "riscv64-unknown-linux-gnu"

; Function Attrs: nofree norecurse nounwind
define dso_local void @vec_add(i32 signext %N, double* noalias nocapture %c, double* noalias nocapture readonly %a, double* noalias nocapture readonly %b, double* noalias nocapture %d) local_unnamed_addr {
; CHECK-LABEL: @vec_add(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP22:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP22]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <vscale x 8 x double> poison, double 3.000000e+00, i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <vscale x 8 x double> [[BROADCAST_SPLATINSERT3]], <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT13:%.*]] = insertelement <vscale x 8 x i1> poison, i1 false, i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT14:%.*]] = shufflevector <vscale x 8 x i1> [[BROADCAST_SPLATINSERT13]], <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 8 x i64> poison, i64 [[INDEX]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 8 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[STEPVEC_BASE:%.*]] = call <vscale x 8 x i64> @llvm.experimental.vector.stepvector.nxv8i64()
; CHECK-NEXT:    [[INDUCTION:%.*]] = add <vscale x 8 x i64> [[BROADCAST_SPLAT2]], [[STEPVEC_BASE]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[TMP1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ule <vscale x 8 x i64> [[INDUCTION]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds double, double* [[C:%.*]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[INDEX]]
; CHECK-NEXT:    [[TMP8:%.*]] = call i64 @llvm.epi.vsetvl(i64 [[TMP7]], i64 3, i64 3)
; CHECK-NEXT:    [[TMP9:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP10:%.*]] = mul i32 [[TMP9]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds double, double* [[TMP6]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = bitcast double* [[TMP11]] to <vscale x 8 x double>*
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 8 x i1> poison, i1 true, i32 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 8 x i1> [[DOTSPLATINSERT]], <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP13:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 8 x double> @llvm.vp.load.nxv8f64.p0nxv8f64(<vscale x 8 x double>* [[TMP12]], i32 8, <vscale x 8 x i1> [[DOTSPLAT]], i32 [[TMP13]])
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP_FCMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.fcmp.nxv8f64(<vscale x 8 x double> [[VP_OP_LOAD]], <vscale x 8 x double> [[BROADCAST_SPLAT4]], i8 4, <vscale x 8 x i1> [[DOTSPLAT]], i32 [[TMP14]])
; CHECK-NEXT:    [[TMP15:%.*]] = select <vscale x 8 x i1> [[DOTSPLAT]], <vscale x 8 x i1> [[VP_OP_FCMP]], <vscale x 8 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds double, double* [[A:%.*]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP17:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP18:%.*]] = mul i32 [[TMP17]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds double, double* [[TMP16]], i32 [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = bitcast double* [[TMP19]] to <vscale x 8 x double>*
; CHECK-NEXT:    [[TMP21:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP_LOAD9:%.*]] = call <vscale x 8 x double> @llvm.vp.load.nxv8f64.p0nxv8f64(<vscale x 8 x double>* [[TMP20]], i32 8, <vscale x 8 x i1> [[DOTSPLAT]], i32 [[TMP21]])
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds double, double* [[B:%.*]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP23:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP24:%.*]] = mul i32 [[TMP23]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds double, double* [[TMP22]], i32 [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = bitcast double* [[TMP25]] to <vscale x 8 x double>*
; CHECK-NEXT:    [[TMP27:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP_LOAD12:%.*]] = call <vscale x 8 x double> @llvm.vp.load.nxv8f64.p0nxv8f64(<vscale x 8 x double>* [[TMP26]], i32 8, <vscale x 8 x i1> [[DOTSPLAT]], i32 [[TMP27]])
; CHECK-NEXT:    [[TMP28:%.*]] = xor <vscale x 8 x i1> [[TMP15]], shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> undef, i1 true, i32 0), <vscale x 8 x i1> undef, <vscale x 8 x i32> zeroinitializer)
; CHECK-NEXT:    [[TMP29:%.*]] = select <vscale x 8 x i1> [[TMP5]], <vscale x 8 x i1> [[TMP28]], <vscale x 8 x i1> [[BROADCAST_SPLAT14]]
; CHECK-NEXT:    [[TMP30:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_OP_LOAD9]], <vscale x 8 x double> [[VP_OP_LOAD12]], metadata !"round.tonearest", metadata !"fpexcept.ignore", <vscale x 8 x i1> [[TMP29]], i32 [[TMP30]])
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds double, double* [[D:%.*]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP32:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP33:%.*]] = mul i32 [[TMP32]], 0
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds double, double* [[TMP31]], i32 [[TMP33]]
; CHECK-NEXT:    [[TMP35:%.*]] = bitcast double* [[TMP34]] to <vscale x 8 x double>*
; CHECK-NEXT:    [[TMP36:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    call void @llvm.vp.store.nxv8f64.p0nxv8f64(<vscale x 8 x double> [[VP_OP]], <vscale x 8 x double>* [[TMP35]], i32 8, <vscale x 8 x i1> [[TMP29]], i32 [[TMP36]])
; CHECK-NEXT:    [[TMP37:%.*]] = select <vscale x 8 x i1> [[TMP5]], <vscale x 8 x i1> [[TMP15]], <vscale x 8 x i1> [[BROADCAST_SPLAT14]]
; CHECK-NEXT:    [[TMP38:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    [[VP_OP15:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP_LOAD9]], <vscale x 8 x double> [[VP_OP_LOAD12]], metadata !"round.tonearest", metadata !"fpexcept.ignore", <vscale x 8 x i1> [[TMP37]], i32 [[TMP38]])
; CHECK-NEXT:    [[TMP39:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP40:%.*]] = mul i32 [[TMP39]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr inbounds double, double* [[TMP6]], i32 [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = bitcast double* [[TMP41]] to <vscale x 8 x double>*
; CHECK-NEXT:    [[TMP43:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK-NEXT:    call void @llvm.vp.store.nxv8f64.p0nxv8f64(<vscale x 8 x double> [[VP_OP15]], <vscale x 8 x double>* [[TMP42]], i32 8, <vscale x 8 x i1> [[TMP37]], i32 [[TMP43]])
; CHECK-NEXT:    [[TMP44:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP45:%.*]] = mul i64 [[TMP44]], 8
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP8]]
; CHECK-NEXT:    [[TMP46:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[TMP46]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], [[LOOP0:!llvm.loop !.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    br i1 true, label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[WIDE_TRIP_COUNT]], [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds double, double* [[C]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP47:%.*]] = load double, double* [[ARRAYIDX]], align 8
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt double [[TMP47]], 3.000000e+00
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds double, double* [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP48:%.*]] = load double, double* [[ARRAYIDX3]], align 8
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds double, double* [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP49:%.*]] = load double, double* [[ARRAYIDX5]], align 8
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[ADD:%.*]] = fadd double [[TMP48]], [[TMP49]]
; CHECK-NEXT:    store double [[ADD]], double* [[ARRAYIDX]], align 8
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       if.else:
; CHECK-NEXT:    [[MUL:%.*]] = fmul double [[TMP48]], [[TMP49]]
; CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds double, double* [[D]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store double [[MUL]], double* [[ARRAYIDX13]], align 8
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]], [[LOOP2:!llvm.loop !.*]]
;
; CHECK1-LABEL: @vec_add(
; CHECK1-NEXT:  entry:
; CHECK1-NEXT:    [[CMP22:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK1-NEXT:    br i1 [[CMP22]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK1:       for.body.preheader:
; CHECK1-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK1-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK1:       vector.ph:
; CHECK1-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], 1
; CHECK1-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i32 0
; CHECK1-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
; CHECK1-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <vscale x 1 x double> poison, double 3.000000e+00, i32 0
; CHECK1-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <vscale x 1 x double> [[BROADCAST_SPLATINSERT3]], <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
; CHECK1-NEXT:    [[BROADCAST_SPLATINSERT13:%.*]] = insertelement <vscale x 1 x i1> poison, i1 false, i32 0
; CHECK1-NEXT:    [[BROADCAST_SPLAT14:%.*]] = shufflevector <vscale x 1 x i1> [[BROADCAST_SPLATINSERT13]], <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
; CHECK1-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK1:       vector.body:
; CHECK1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK1-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[INDEX]], i32 0
; CHECK1-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 1 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
; CHECK1-NEXT:    [[STEPVEC_BASE:%.*]] = call <vscale x 1 x i64> @llvm.experimental.vector.stepvector.nxv1i64()
; CHECK1-NEXT:    [[INDUCTION:%.*]] = add <vscale x 1 x i64> [[BROADCAST_SPLAT2]], [[STEPVEC_BASE]]
; CHECK1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 0
; CHECK1-NEXT:    [[TMP2:%.*]] = add i64 [[TMP1]], 0
; CHECK1-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 1
; CHECK1-NEXT:    [[TMP4:%.*]] = add i64 [[INDEX]], [[TMP3]]
; CHECK1-NEXT:    [[TMP5:%.*]] = icmp ule <vscale x 1 x i64> [[INDUCTION]], [[BROADCAST_SPLAT]]
; CHECK1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds double, double* [[C:%.*]], i64 [[TMP4]]
; CHECK1-NEXT:    [[TMP7:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[INDEX]]
; CHECK1-NEXT:    [[TMP8:%.*]] = call i64 @llvm.epi.vsetvl(i64 [[TMP7]], i64 3, i64 0)
; CHECK1-NEXT:    [[TMP9:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP10:%.*]] = mul i32 [[TMP9]], 0
; CHECK1-NEXT:    [[TMP11:%.*]] = getelementptr inbounds double, double* [[TMP6]], i32 [[TMP10]]
; CHECK1-NEXT:    [[TMP12:%.*]] = bitcast double* [[TMP11]] to <vscale x 1 x double>*
; CHECK1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 1 x i1> poison, i1 true, i32 0
; CHECK1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 1 x i1> [[DOTSPLATINSERT]], <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
; CHECK1-NEXT:    [[TMP13:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 1 x double> @llvm.vp.load.nxv1f64.p0nxv1f64(<vscale x 1 x double>* [[TMP12]], i32 8, <vscale x 1 x i1> [[DOTSPLAT]], i32 [[TMP13]])
; CHECK1-NEXT:    [[TMP14:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP_FCMP:%.*]] = call <vscale x 1 x i1> @llvm.vp.fcmp.nxv1f64(<vscale x 1 x double> [[VP_OP_LOAD]], <vscale x 1 x double> [[BROADCAST_SPLAT4]], i8 4, <vscale x 1 x i1> [[DOTSPLAT]], i32 [[TMP14]])
; CHECK1-NEXT:    [[TMP15:%.*]] = select <vscale x 1 x i1> [[DOTSPLAT]], <vscale x 1 x i1> [[VP_OP_FCMP]], <vscale x 1 x i1> zeroinitializer
; CHECK1-NEXT:    [[TMP16:%.*]] = getelementptr inbounds double, double* [[A:%.*]], i64 [[TMP4]]
; CHECK1-NEXT:    [[TMP17:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP18:%.*]] = mul i32 [[TMP17]], 0
; CHECK1-NEXT:    [[TMP19:%.*]] = getelementptr inbounds double, double* [[TMP16]], i32 [[TMP18]]
; CHECK1-NEXT:    [[TMP20:%.*]] = bitcast double* [[TMP19]] to <vscale x 1 x double>*
; CHECK1-NEXT:    [[TMP21:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP_LOAD9:%.*]] = call <vscale x 1 x double> @llvm.vp.load.nxv1f64.p0nxv1f64(<vscale x 1 x double>* [[TMP20]], i32 8, <vscale x 1 x i1> [[DOTSPLAT]], i32 [[TMP21]])
; CHECK1-NEXT:    [[TMP22:%.*]] = getelementptr inbounds double, double* [[B:%.*]], i64 [[TMP4]]
; CHECK1-NEXT:    [[TMP23:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP24:%.*]] = mul i32 [[TMP23]], 0
; CHECK1-NEXT:    [[TMP25:%.*]] = getelementptr inbounds double, double* [[TMP22]], i32 [[TMP24]]
; CHECK1-NEXT:    [[TMP26:%.*]] = bitcast double* [[TMP25]] to <vscale x 1 x double>*
; CHECK1-NEXT:    [[TMP27:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP_LOAD12:%.*]] = call <vscale x 1 x double> @llvm.vp.load.nxv1f64.p0nxv1f64(<vscale x 1 x double>* [[TMP26]], i32 8, <vscale x 1 x i1> [[DOTSPLAT]], i32 [[TMP27]])
; CHECK1-NEXT:    [[TMP28:%.*]] = xor <vscale x 1 x i1> [[TMP15]], shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> undef, i1 true, i32 0), <vscale x 1 x i1> undef, <vscale x 1 x i32> zeroinitializer)
; CHECK1-NEXT:    [[TMP29:%.*]] = select <vscale x 1 x i1> [[TMP5]], <vscale x 1 x i1> [[TMP28]], <vscale x 1 x i1> [[BROADCAST_SPLAT14]]
; CHECK1-NEXT:    [[TMP30:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP:%.*]] = call <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double> [[VP_OP_LOAD9]], <vscale x 1 x double> [[VP_OP_LOAD12]], metadata !"round.tonearest", metadata !"fpexcept.ignore", <vscale x 1 x i1> [[TMP29]], i32 [[TMP30]])
; CHECK1-NEXT:    [[TMP31:%.*]] = getelementptr inbounds double, double* [[D:%.*]], i64 [[TMP4]]
; CHECK1-NEXT:    [[TMP32:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP33:%.*]] = mul i32 [[TMP32]], 0
; CHECK1-NEXT:    [[TMP34:%.*]] = getelementptr inbounds double, double* [[TMP31]], i32 [[TMP33]]
; CHECK1-NEXT:    [[TMP35:%.*]] = bitcast double* [[TMP34]] to <vscale x 1 x double>*
; CHECK1-NEXT:    [[TMP36:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    call void @llvm.vp.store.nxv1f64.p0nxv1f64(<vscale x 1 x double> [[VP_OP]], <vscale x 1 x double>* [[TMP35]], i32 8, <vscale x 1 x i1> [[TMP29]], i32 [[TMP36]])
; CHECK1-NEXT:    [[TMP37:%.*]] = select <vscale x 1 x i1> [[TMP5]], <vscale x 1 x i1> [[TMP15]], <vscale x 1 x i1> [[BROADCAST_SPLAT14]]
; CHECK1-NEXT:    [[TMP38:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    [[VP_OP15:%.*]] = call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[VP_OP_LOAD9]], <vscale x 1 x double> [[VP_OP_LOAD12]], metadata !"round.tonearest", metadata !"fpexcept.ignore", <vscale x 1 x i1> [[TMP37]], i32 [[TMP38]])
; CHECK1-NEXT:    [[TMP39:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP40:%.*]] = mul i32 [[TMP39]], 0
; CHECK1-NEXT:    [[TMP41:%.*]] = getelementptr inbounds double, double* [[TMP6]], i32 [[TMP40]]
; CHECK1-NEXT:    [[TMP42:%.*]] = bitcast double* [[TMP41]] to <vscale x 1 x double>*
; CHECK1-NEXT:    [[TMP43:%.*]] = trunc i64 [[TMP8]] to i32
; CHECK1-NEXT:    call void @llvm.vp.store.nxv1f64.p0nxv1f64(<vscale x 1 x double> [[VP_OP15]], <vscale x 1 x double>* [[TMP42]], i32 8, <vscale x 1 x i1> [[TMP37]], i32 [[TMP43]])
; CHECK1-NEXT:    [[TMP44:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP8]]
; CHECK1-NEXT:    [[TMP45:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK1-NEXT:    br i1 [[TMP45]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], [[LOOP0:!llvm.loop !.*]]
; CHECK1:       middle.block:
; CHECK1-NEXT:    br i1 true, label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK1:       scalar.ph:
; CHECK1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[WIDE_TRIP_COUNT]], [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK1-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK1:       for.cond.cleanup.loopexit:
; CHECK1-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK1:       for.cond.cleanup:
; CHECK1-NEXT:    ret void
; CHECK1:       for.body:
; CHECK1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds double, double* [[C]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    [[TMP46:%.*]] = load double, double* [[ARRAYIDX]], align 8
; CHECK1-NEXT:    [[CMP1:%.*]] = fcmp olt double [[TMP46]], 3.000000e+00
; CHECK1-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds double, double* [[A]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    [[TMP47:%.*]] = load double, double* [[ARRAYIDX3]], align 8
; CHECK1-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds double, double* [[B]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    [[TMP48:%.*]] = load double, double* [[ARRAYIDX5]], align 8
; CHECK1-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK1:       if.then:
; CHECK1-NEXT:    [[ADD:%.*]] = fadd double [[TMP47]], [[TMP48]]
; CHECK1-NEXT:    store double [[ADD]], double* [[ARRAYIDX]], align 8
; CHECK1-NEXT:    br label [[FOR_INC]]
; CHECK1:       if.else:
; CHECK1-NEXT:    [[MUL:%.*]] = fmul double [[TMP47]], [[TMP48]]
; CHECK1-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds double, double* [[D]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    store double [[MUL]], double* [[ARRAYIDX13]], align 8
; CHECK1-NEXT:    br label [[FOR_INC]]
; CHECK1:       for.inc:
; CHECK1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK1-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK1-NEXT:    br i1 [[EXITCOND]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]], [[LOOP2:!llvm.loop !.*]]
;
entry:
  %cmp22 = icmp sgt i32 %N, 0
  br i1 %cmp22, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext i32 %N to i64
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.inc
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  ret void

for.body:                                         ; preds = %for.inc, %for.body.preheader
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.inc ]
  %arrayidx = getelementptr inbounds double, double* %c, i64 %indvars.iv
  %0 = load double, double* %arrayidx, align 8
  %cmp1 = fcmp olt double %0, 3.000000e+00
  %arrayidx3 = getelementptr inbounds double, double* %a, i64 %indvars.iv
  %1 = load double, double* %arrayidx3, align 8
  %arrayidx5 = getelementptr inbounds double, double* %b, i64 %indvars.iv
  %2 = load double, double* %arrayidx5, align 8
  br i1 %cmp1, label %if.then, label %if.else

if.then:                                          ; preds = %for.body
  %add = fadd double %1, %2
  store double %add, double* %arrayidx, align 8
  br label %for.inc

if.else:                                          ; preds = %for.body
  %mul = fmul double %1, %2
  %arrayidx13 = getelementptr inbounds double, double* %d, i64 %indvars.iv
  store double %mul, double* %arrayidx13, align 8
  br label %for.inc

for.inc:                                          ; preds = %if.then, %if.else
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.cond.cleanup.loopexit, label %for.body
}
