; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+experimental-v -S \
; RUN:    -loop-vectorize -vector-register-width-factor=8 < %s -o - | FileCheck %s
; RUN: opt -mtriple riscv64 -mattr +m,+a,+f,+d,+experimental-v -S \
; RUN:    -loop-vectorize < %s -o - | FileCheck %s --check-prefix=CHECK1
; ModuleID = 'vfadd32.c'
source_filename = "vfadd32.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-linux-gnu"

; Function Attrs: nofree norecurse nounwind
define dso_local void @vfadd32(float* noalias nocapture %dz, float* noalias nocapture readonly %dx, float* noalias nocapture readonly %dy, i32 signext %n) local_unnamed_addr #0 {
; CHECK-LABEL: @vfadd32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP10:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP10]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_END:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[WIDE_TRIP_COUNT]], [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 16
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[WIDE_TRIP_COUNT]], [[TMP3]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[N_MOD_VF]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP5:%.*]] = mul i64 [[TMP4]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = mul i64 [[TMP6]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, float* [[DX:%.*]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP11:%.*]] = mul i32 [[TMP10]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, float* [[TMP9]], i32 [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast float* [[TMP12]] to <vscale x 16 x float>*
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x float>, <vscale x 16 x float>* [[TMP13]], align 4, [[TBAA2:!tbaa !.*]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds float, float* [[DY:%.*]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP15:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP16:%.*]] = mul i32 [[TMP15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds float, float* [[TMP14]], i32 [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = bitcast float* [[TMP17]] to <vscale x 16 x float>*
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 16 x float>, <vscale x 16 x float>* [[TMP18]], align 4, [[TBAA2]]
; CHECK-NEXT:    [[TMP19:%.*]] = fadd <vscale x 16 x float> [[WIDE_LOAD]], [[WIDE_LOAD1]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds float, float* [[DZ:%.*]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP21:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP22:%.*]] = mul i32 [[TMP21]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, float* [[TMP20]], i32 [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast float* [[TMP23]] to <vscale x 16 x float>*
; CHECK-NEXT:    store <vscale x 16 x float> [[TMP19]], <vscale x 16 x float>* [[TMP24]], align 4, [[TBAA2]]
; CHECK-NEXT:    [[TMP25:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP26:%.*]] = mul i64 [[TMP25]], 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP26]]
; CHECK-NEXT:    [[TMP27:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP27]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], [[LOOP6:!llvm.loop !.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[WIDE_TRIP_COUNT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[FOR_END_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, float* [[DX]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP28:%.*]] = load float, float* [[ARRAYIDX]], align 4, [[TBAA2]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, float* [[DY]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP29:%.*]] = load float, float* [[ARRAYIDX2]], align 4, [[TBAA2]]
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[TMP28]], [[TMP29]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, float* [[DZ]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store float [[ADD]], float* [[ARRAYIDX4]], align 4, [[TBAA2]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_END_LOOPEXIT]], label [[FOR_BODY]], [[LOOP8:!llvm.loop !.*]]
; CHECK:       for.end.loopexit:
; CHECK-NEXT:    br label [[FOR_END]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
; CHECK1-LABEL: @vfadd32(
; CHECK1-NEXT:  entry:
; CHECK1-NEXT:    [[CMP10:%.*]] = icmp sgt i32 [[N:%.*]], 0
; CHECK1-NEXT:    br i1 [[CMP10]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_END:%.*]]
; CHECK1:       for.body.preheader:
; CHECK1-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N]] to i64
; CHECK1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 2
; CHECK1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[WIDE_TRIP_COUNT]], [[TMP1]]
; CHECK1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK1:       vector.ph:
; CHECK1-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 2
; CHECK1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[WIDE_TRIP_COUNT]], [[TMP3]]
; CHECK1-NEXT:    [[N_VEC:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[N_MOD_VF]]
; CHECK1-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK1:       vector.body:
; CHECK1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[TMP5:%.*]] = mul i64 [[TMP4]], 0
; CHECK1-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 0
; CHECK1-NEXT:    [[TMP7:%.*]] = mul i64 [[TMP6]], 1
; CHECK1-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], [[TMP7]]
; CHECK1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, float* [[DX:%.*]], i64 [[TMP8]]
; CHECK1-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP11:%.*]] = mul i32 [[TMP10]], 0
; CHECK1-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, float* [[TMP9]], i32 [[TMP11]]
; CHECK1-NEXT:    [[TMP13:%.*]] = bitcast float* [[TMP12]] to <vscale x 2 x float>*
; CHECK1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x float>, <vscale x 2 x float>* [[TMP13]], align 4, [[TBAA2:!tbaa !.*]]
; CHECK1-NEXT:    [[TMP14:%.*]] = getelementptr inbounds float, float* [[DY:%.*]], i64 [[TMP8]]
; CHECK1-NEXT:    [[TMP15:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP16:%.*]] = mul i32 [[TMP15]], 0
; CHECK1-NEXT:    [[TMP17:%.*]] = getelementptr inbounds float, float* [[TMP14]], i32 [[TMP16]]
; CHECK1-NEXT:    [[TMP18:%.*]] = bitcast float* [[TMP17]] to <vscale x 2 x float>*
; CHECK1-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 2 x float>, <vscale x 2 x float>* [[TMP18]], align 4, [[TBAA2]]
; CHECK1-NEXT:    [[TMP19:%.*]] = fadd <vscale x 2 x float> [[WIDE_LOAD]], [[WIDE_LOAD1]]
; CHECK1-NEXT:    [[TMP20:%.*]] = getelementptr inbounds float, float* [[DZ:%.*]], i64 [[TMP8]]
; CHECK1-NEXT:    [[TMP21:%.*]] = call i32 @llvm.vscale.i32()
; CHECK1-NEXT:    [[TMP22:%.*]] = mul i32 [[TMP21]], 0
; CHECK1-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, float* [[TMP20]], i32 [[TMP22]]
; CHECK1-NEXT:    [[TMP24:%.*]] = bitcast float* [[TMP23]] to <vscale x 2 x float>*
; CHECK1-NEXT:    store <vscale x 2 x float> [[TMP19]], <vscale x 2 x float>* [[TMP24]], align 4, [[TBAA2]]
; CHECK1-NEXT:    [[TMP25:%.*]] = call i64 @llvm.vscale.i64()
; CHECK1-NEXT:    [[TMP26:%.*]] = mul i64 [[TMP25]], 2
; CHECK1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP26]]
; CHECK1-NEXT:    [[TMP27:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK1-NEXT:    br i1 [[TMP27]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], [[LOOP6:!llvm.loop !.*]]
; CHECK1:       middle.block:
; CHECK1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[WIDE_TRIP_COUNT]], [[N_VEC]]
; CHECK1-NEXT:    br i1 [[CMP_N]], label [[FOR_END_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK1:       scalar.ph:
; CHECK1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK1-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK1:       for.body:
; CHECK1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, float* [[DX]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    [[TMP28:%.*]] = load float, float* [[ARRAYIDX]], align 4, [[TBAA2]]
; CHECK1-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, float* [[DY]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    [[TMP29:%.*]] = load float, float* [[ARRAYIDX2]], align 4, [[TBAA2]]
; CHECK1-NEXT:    [[ADD:%.*]] = fadd float [[TMP28]], [[TMP29]]
; CHECK1-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, float* [[DZ]], i64 [[INDVARS_IV]]
; CHECK1-NEXT:    store float [[ADD]], float* [[ARRAYIDX4]], align 4, [[TBAA2]]
; CHECK1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK1-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK1-NEXT:    br i1 [[EXITCOND]], label [[FOR_END_LOOPEXIT]], label [[FOR_BODY]], [[LOOP8:!llvm.loop !.*]]
; CHECK1:       for.end.loopexit:
; CHECK1-NEXT:    br label [[FOR_END]]
; CHECK1:       for.end:
; CHECK1-NEXT:    ret void
;
entry:
  %cmp10 = icmp sgt i32 %n, 0
  br i1 %cmp10, label %for.body.preheader, label %for.end

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext i32 %n to i64
  br label %for.body

for.body:                                         ; preds = %for.body, %for.body.preheader
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds float, float* %dx, i64 %indvars.iv
  %0 = load float, float* %arrayidx, align 4, !tbaa !2
  %arrayidx2 = getelementptr inbounds float, float* %dy, i64 %indvars.iv
  %1 = load float, float* %arrayidx2, align 4, !tbaa !2
  %add = fadd float %0, %1
  %arrayidx4 = getelementptr inbounds float, float* %dz, i64 %indvars.iv
  store float %add, float* %arrayidx4, align 4, !tbaa !2
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.end.loopexit, label %for.body

for.end.loopexit:                                 ; preds = %for.body
  br label %for.end

for.end:                                          ; preds = %for.end.loopexit, %entry
  ret void
}

attributes #0 = { nofree norecurse nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-features"="+a,+c,+d,+experimental-v,+f,+m,-relax" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.0 (git@repo.hca.bsc.es:EPI/System-Software/llvm-mono.git 6c96ed45a7b0120200aea55d2099a8cf001c674b)"}
!2 = !{!3, !3, i64 0}
!3 = !{!"float", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}
